### ISSUE TITLE
Add the possibility of adding a UA-code from Google Analytics

### ISSUE THREAD

**Issue by ocorcho** [dgarijo/Widoco#100]
So that it can be added in the main index HTML page to be deployed, so as to keep track of the visitors to the site.

**Comment by dgarijo** [comment]
As far as I know, you need a key to generate the snippet that has to be added to the page. I can add a field to introduce the code, but i am afraid that will be it.
I will look further into this when I have more time.

**Comment by dgarijo** [comment]
I am familiar with analytics, this should only mean paste a code snippet with the code on the main index page. I will try to push something soon addressing this issue.

**Comment by dgarijo** [comment]
Addressed in release v1.4.4 https://github.com/dgarijo/Widoco/releases/tag/v1.4.4
