### ISSUE TITLE
If an evaluation is provided, add the link in the html

### ISSUE THREAD

**Issue by dgarijo** [dgarijo/Widoco#112]
If the oops web service is invoked this would be a great addition. Or at least the pointer to the web service.

**Comment by dgarijo** [comment]
Or provide the link automatically when doing through Widoco.

**Comment by HaydarAk** [comment]
Is there anything planned for this in the near future ? 

I am updating my widoco documentation on a regular basis. For the OOPS! evaluation results, I use a simple python script to add a line to the index.html (if the `OOPSeval.html` file exists)

`<dt>Evaluation:</dt><dd><a href="OOPSEvaluation/OOPSeval.html#" target="_blank"><img src="https://img.shields.io/badge/Evaluate_with-OOPS! (OntOlogy Pitfall Scanner!)-blue.svg" alt="Evaluate with OOPS!" /></a></dd>`

The option to reference to the OOPS results (if evaluation results are available) would be nice
![OOPS](https://user-images.githubusercontent.com/7315550/72153059-1bfac700-33ad-11ea-8ca3-33cc73b64f62.PNG)

**Comment by dgarijo** [comment]
@HaydarAk,
when I looked into this there was a slight problem because the documentation is generated before the OOPS! report, and hence I would have to add some changes in the UI or edit the HTML after it is generated. I will have a look as soon as I can, but it may take time.
Thanks for your interest! 
Best,
Daniel

**Comment by dgarijo** [comment]
@HaydarAk, I incorporated this and released it: https://github.com/dgarijo/Widoco/releases/tag/v1.4.13
Now you don't need the script! :)
