### ISSUE TITLE
Reused ontology namespaces

### ISSUE THREAD

**Issue by filiprd** [dgarijo/Widoco#116]
In some ceases, namespaces are not properly loaded form the ontology and they are changed in the documentation files.
For example, in https://raw.githubusercontent.com/filiprd/QualityModelOntology/master/QualityModelOntology.owl eval is changed to evaluationresultsontology.

**Comment by dgarijo** [comment]
This issue comes from the way LODE identifies namespaces. I might redo this part in a future release.

**Comment by filiprd** [comment]
Thanks.

**Comment by dgarijo** [comment]
Fixed in `develop` branch
