### ISSUE TITLE
odd/wrong linknames added

### ISSUE THREAD

**Issue by pipauwel** [dgarijo/Widoco#123]
Odd links are sometimes generated (creator039 for IfcSpatialElementType). Not sure what is causing this. Luckily, the link matches at least.

<.li>
<.a href="#http://purl.org/dc/elements/1.1/creator039" title="http://www.buildingsmart-tech.org/ifcOWL/IFC4_ADD1#IfcSpatialElementType">
<.span>ifc spatial element type</span>
<./a>
<./li>

<.div class="entity" id="http://purl.org/dc/elements/1.1/creator039">
<.h3>ifc spatial element type<.sup class="type-c" title="class">c<./sup>
<.span class="backlink"> back to <.a href="#toc">ToC</a> or <.a href="#classes">Class ToC<./a><./span>
<./h3>
<./div>

**Comment by dgarijo** [comment]
This corresponds to this ontology: http://users.ugent.be/~pipauwel/IFC4_ADD1/IFC4_ADD1.rdf
Check it out

**Comment by pipauwel** [comment]
I have added these ifcOWL ontologies at:
- www.buildingsmart-tech.org/future/linked-data/
- http://users.ugent.be/~pipauwel/
- https://github.com/pipauwel/ifcOWL
Feel free to test the Widoco with these ontologies and list remarks and issues in the github page.

**Comment by dgarijo** [comment]
I have generated the documentation of https://github.com/pipauwel/ifcOWL/blob/master/IFC4_ADD1.rdf (the  link I had in my previous comment leads to a 404 now) and no odd links have appeared. A previous commit must  have cleared this issue. Feel free to reopen it :)
