### ISSUE TITLE
no result if owl:imports link is not online

### ISSUE THREAD

**Issue by pipauwel** [dgarijo/Widoco#125]
if an owl:imports link refers to an ontology URI that is not online, the documentation generator fails. Without the owl:imports link, everything goes fine.

**Comment by dgarijo** [comment]
I have to test this. An example ontology where this happens would help me a lot here :)

**Comment by pipauwel** [comment]
You can find an example at : http://users.ugent.be/~pipauwel/wrongimportlink_express.owl

The line <Import>http://www.co-ode.org/ontologies/list.owl#</Import> points to an unexisting location. Not much seemed to happen when I tested it (couple of days ago). The correct link is <Import>http://owl.cs.manchester.ac.uk/wp-content/uploads/2015/07/list.owl_.txt</Import>.

Of course, everyone should use the correct link, but perhaps you can include a safety check and some return message?

**Comment by dgarijo** [comment]
Ok now an error is returned. Previously you could see everything if you executed the program through a command line. However I have to recognize that logging is not exhaustive.
