### ISSUE TITLE
Prepare the content negotiation bundle

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#154]

**Comment by dgarijo** [comment]
Now this is easy because I do a local copy of the ontology.

**Comment by jarsomatic** [comment]
@dgarijo I didn't get it, are you referring to a specific case?

**Comment by ahmad88me** [comment]
@dgarijo I didn't get it, are you referring to a specific case?

**Comment by dgarijo** [comment]
I haven't done it yet. But with the latest changes it's easy :)
