### ISSUE TITLE
Wrong license text for CC 4.0

### ISSUE THREAD

**Issue by stain** [dgarijo/Widoco#157]
http://wf4ever.github.io/ro/2016-01-28/ro/index-en.html
made from 
https://github.com/wf4ever/ro/blob/master/ro.owl

wrongly says

> This work is licensed under a license: Creative Commons Attribution 3.0 License.

but the link goes correctly to the 4.0 license http://creativecommons.org/licenses/by/4.0/

**Comment by dgarijo** [comment]
I think there is an error when calling the web service that has the license metadata. I will check this out.

**Comment by dgarijo** [comment]
It seems to be working fine now.
However note that the url of the ontology is not https://raw.githubusercontent.com/wf4ever/ro/master/ro.owl but purl.org/w4ever/ro. The system will use that one to extract the metadata from (preferred namespace uri)
