### ISSUE TITLE
Ability to provide external serializations using widoco.config

### ISSUE THREAD

**Issue by nandana** [dgarijo/Widoco#176]
Will it be possible to provide the URLs for different serializations of the ontology using the widico.config?

In our case, the ontology already has serializations of different RDF formats in given URLs (with vocabularium) and we want to specify them in the config.

jsonLDSerialization=http://ont-loupe.linkeddata.es/def/core.jsonld
rdfXmlSerialization=http://ont-loupe.linkeddata.es/def/core.rdf
turtuleSerialization=http://ont-loupe.linkeddata.es/def/core.ttl

Finally we want them to be listed in the documentation similar to how it's currently done.

![widoco](https://cloud.githubusercontent.com/assets/204855/16455497/d74d9358-3e14-11e6-8d2e-dd453042a9d0.png)

**Comment by dgarijo** [comment]
Use https://img.shields.io/badge/Format-http://banana-blue.svg
