### ISSUE TITLE
Question for multiple languages flag

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#193]
@dgarijo 
in the readme, it is mention as follow: [-lang lang1-lang2]
so it would be something like "-lang es-en" ? or "-lang es en"?

**Comment by dgarijo** [comment]
Hi @ahmad88me,
it is with "-" between languages: -lang en-es-pt. Before I used ";" but if you are using the command line as part of a script in certain languages they consider it an end to the line.

**Comment by ahmad88me** [comment]
@dgarijo thx, I'll try it out
