### ISSUE TITLE
Improve documentation of properties in cases where they are not defined just as rdf:Property, etc.

### ISSUE THREAD

**Issue by ocorcho** [dgarijo/Widoco#194]
In this ontology file:
https://github.com/localidata/local-data-aragopedia/blob/master/data/dump/DatosTTL/codelists/properties.ttl

there are properties that are defined as 
XXXX a rdf:Property, qb:MeasureProperty

As a result, in the documentation, such properties are created as properties (because of rdf:Property) plus named individuals (because of qb:MeasureProperty). However, this is somehow incorrect in the documentation that is generated, and leads to confusion. 

The named individuals should be hence removed from the documentation.

**Comment by dgarijo** [comment]
This one requires me to dive into the fantastic XSLT spreadsheet of LODE, so this issue might take a while to be solved.

**Comment by dgarijo** [comment]
I have taken a deeper look into the ontology. The named individuals are declared. If you want to create properties, then you should say that they are subPropertyOf. I have loaded the ontology in Protege and it also recognizes the named individuals, so this is not a problem of the XSLT conversion.

If you want to ignore the individuals, you can execute Widoco with the -ignoreIndividuals flag
