### ISSUE TITLE
htaccess is not generated with the below options

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#199]
When I call Widoco with the below options, the htaccess is not generated

java -jar  -Dfile.encoding=utf-8 /home/ubuntu/Widoco/JAR/widoco-jar-with-dependencies.jar  -rewriteAll  -ontFile 'SAREF4ENV/ontology/saref4envi.ttl' -outFolder 'OnToology/SAREF4ENV/ontology/saref4envi.ttl/documentation' -getOntologyMetadata  -saveConfig OnToology/SAREF4ENV/ontology/saref4envi.ttl/documentation/saref4envi.ttl.widoco.conf -htaccess

**Comment by dgarijo** [comment]
@ahmad88me,
I cannot reproduce the error, the htaccess is produced properly. I am using Widoco 1.2.3 (latest release). I attach all the files being produced. This is the command I executed:
>java -jar -Dfile.encoding=utf-8 widoco-1.2.3-jar-with-dependencies.jar -rewriteAll -ontFile testOntos\saref4envi.ttl -outFolder doc -getOntologyMetadata -saveConfig sarefconf.properties -htaccess

Note that in the command you posted you included all the urls between quotation marks except the ones at the end.
[doc.zip](https://github.com/dgarijo/Widoco/files/722694/doc.zip)

**Comment by ahmad88me** [comment]
@dgarijo does the use of the below flags affect the generation of htaccess in anyway?
 -getOntologyMetadata -saveConfig

**Comment by dgarijo** [comment]
No, none of them should. The first one aims to retrieve metadata from the ontology. The second one just saves the configuration into a properties file. If you still have the issue, I recommend you to get version 1.2.3. It worked for me
