### ISSUE TITLE
If WIDOCO is opened in Java versions under 1.8, an exception will occur

### ISSUE THREAD

**Issue by dgarijo** [dgarijo/Widoco#241]
The exception is now documented in the readme.md file of the project.
However, I should check the version and issue a message if that is the case.

Issue from @ahmad88me

**Comment by ahmad88me** [comment]
Version: 1.7 
OS: ubuntu 14.04 
Error message:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: widoco/gui/GuiController ...
```

**Comment by dgarijo** [comment]
Use  System.getProperty("java.version") and produce an error

**Comment by dgarijo** [comment]
Fixed in https://github.com/dgarijo/Widoco/commit/0e903d9fb89ccbbbdbb1e5c2e65763a36419dbf9
