### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by dgarijo** [dgarijo/Widoco#244]
It may help guiding users when using the tool.
This issue was proposed by the **ISWC2017 reviewers.**

**Comment by coolharsh55** [comment]
Would these go in the wizard/help menu, or on the documentation page?

**Comment by dgarijo** [comment]
They will be on the documentation page. I will point to them from the menu too.

**Comment by coolharsh55** [comment]
Could you also add descriptions of how the introduction, overview, etc. sections are to be added? Currently, the only way (as much as I could see) to add them is via the wizard file selection, and it's still not clear that a HTML markup is expected. And if it needs to have the ordering, then the title class should be "list".

**Comment by AlasdairGray** [comment]
A tutorial on usage would be really helpful. It seems that you should use the wizard for the first time generation but then a configuration file from there on. However, when using from the command line I don't see how to configure it to generate the metadata but not different sections. 

Also with the wizard you could configure which sections you wanted but how do you do that with the command line?

**Comment by dgarijo** [comment]
@AlasdairGray 
thanks for the feedback. The configuration file is optional every time. It's an alternate way of providing missing vocabulary metadata. There is a flag (-saveConfig) to save it when you run the console if you are interested.

The abstract can be read from the ontology metadata too if there is a dc:abstract or similar (see the ongoing guidelines: http://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html#abs)

Finally, in the command line you can either produce all sections or just the cross reference section with the -crossRef option. I did it this way because so far nobody asked for any other section in particular.

Please feel free to extend the readme file addressing some of your concerns if something is not clear.
