### ISSUE TITLE
The tests are written just for Windows

### ISSUE THREAD

**Issue by marianofl1971** [dgarijo/Widoco#248]
Inside the code of the tests, the paths to the used ontologies have "\\" instead of "/", therefore, they fail in Linux.

**Comment by dgarijo** [comment]
I have been changing this to File.PathSeparator so they work un Unix too. WIll push this in the next release. Thanks for noticing.

**Comment by marianofl1971** [comment]
De nada. El software me ha resultado de gran ayuda.

Mariano

2017-10-06 16:31 GMT+02:00 Daniel Garijo <notifications@github.com>:

**Comment by dgarijo** [comment]
@binfalse just did a pull request addressing this issue :)
