### ISSUE TITLE
Add introduction, overview sections using filepath

### ISSUE THREAD

**Issue by coolharsh55** [dgarijo/Widoco#249]
Allow option to specify the file to be imported for Introduction and other sections. This can be helpful in creating the introduction and other sections and keeping them in separate files while the ontology documentation can be updated.

**Comment by dgarijo** [comment]
You can do this via the interface, in step 3, right?

**Comment by coolharsh55** [comment]
Yes, but not via the command line, or the config file.

**Comment by dgarijo** [comment]
Hmm, if you add the -crossRef option, then only the crossRef file will be rewritten. That way the rest of the files won't be rewritten in case you had them already there.

**Comment by coolharsh55** [comment]
> The -crossRef option will ONLY generate the overview and cross reference sections.

I assumed that this meant that only the overview (not the introduction and other sections) and cross-ref section were re-generated.

**Comment by dgarijo** [comment]
yes, exactly. So if you have your introduction and other sections in your folder, only the crossref section and overview will be rewritten. Therefore  you can keep them separately while the documentation is updated. Isn't that what you aim to achieve?

**Comment by coolharsh55** [comment]
Yes, it is. This is only possible if Widoco is given the existing output directory, if I understand this correctly?

**Comment by dgarijo** [comment]
Yes. I should add that clarification. Thanks!

**Comment by coolharsh55** [comment]
Great. I was worried I might have to find a hacky-way to solve this.

**Comment by dgarijo** [comment]
We had to deal with this for our integration with OnToology too :)
An example:
java -jar widoco.jar -ontURI https://raw.githubusercontent.com/ahmad88me/demo/master/alo.owl# -outFolder doc  -rewriteAll -useCustomStyle -lang en -includeImportedOntologies -crossRef -webVowl

**Comment by dgarijo** [comment]
Since there were no further comments, I will close the issue.
