### ISSUE TITLE
Different directory structure when using htaccess

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#250]
When I use –htaccess option , the directory structure generated is different for different ontologies.

For some it is like

   .htaccess
   Index_en.html
   Provenance

For some it is like

  .htaccess
  doc/

And the index files are within the doc folder.

Can you clarify why this might be happening.

**Comment by dgarijo** [comment]
Yes, it's done on purpose.  This is due the content negotiation (hash versus slash). For the slash I needed a rewrite base folder, and I didn't want to prompt the user about it. See: https://www.w3.org/TR/swbp-vocab-pub/

**Comment by kartgk** [comment]
Great, thanks for pointing to the information.

**Comment by dgarijo** [comment]
No worries! That said, you can change the structure a little bit, but you will have change the htaccess accordingly or the content negotiation will be broken.

**Comment by Maximvdw** [comment]
Its an old closed issue - but it seems this also occurs with slash separators without htacces generation, which does not seem to be an ideal scenario since the issue is not present

**Comment by dgarijo** [comment]
This is the default scenario for slash vocabularies. The rationale is so they can be easily deployed afterwards.

**Comment by Maximvdw** [comment]
> This is the default scenario for slash vocabularies. The rationale is so they can be easily deployed afterwards.

While I understand the rationale, in cases where deployment is automatically - this is a bit annoying with additional work to move all files out of the doc directory

**Comment by dgarijo** [comment]
I see. Open a new issue for a feature request then :)
Or even better, contribute with a fix :D

**Comment by dgarijo** [comment]
It could be added as a new flag

**Comment by Maximvdw** [comment]
Will look into a PR mid May. What about a combination of "outFolder" when the htaccess flag is missing? That way there is no need for another flag - and those who want a doc directory just have to append it themselves to their existing outFolder flag

**Comment by dgarijo** [comment]
so basically, if there is no `htaccess` and the vocabulary is slash, just put it under `outfolder`? That would work, yep
