### ISSUE TITLE
Disable Download Serialization on Page

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#251]
We have an official manually edited format for ontology files and would not want the user to have another serialization. Is there a way to turn off or not display the Download Serialization on the ontology page.

**Comment by dgarijo** [comment]
At the moment it's added by default. I assumed everyone would want this. I will try to make it configurable in a next release.

**Comment by kartgk** [comment]
Great. Thanks for considering the enhancement.

**Comment by kartgk** [comment]
@dgarijo Can you please revisit this.

**Comment by kartgk** [comment]
Awesome. Thanks.
