### ISSUE TITLE
Documentation Not Generated And no helpful error message

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#257]
I m trying to generate documentation for the attached ontology. 

java -jar ./widoco-1.4.1-jar-with-dependencies.jar -ontFile "CommercialLoans.rdf"  -rewriteAll -lang en
[CommercialLoans.txt](https://github.com/dgarijo/Widoco/files/1397311/CommercialLoans.txt)

Pls change attached extension to .rdf.

I tried with other options ( importedOntologies, ...),   no luck.  

Just get the following message, and it doesnt help. 

**_ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.

%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%nCould not load the ontology
Generating documentation for CommercialLoans.rdf in lang en
Error while generating the documentation null_**

**Comment by kartgk** [comment]
I tried generating documentation from the LODE website and that worked

http://www.essepuntato.it/lode/

**Comment by dgarijo** [comment]
I tried loading the attached ontology in Protege 5.2.0 , and it failed (no classes recognized)
I have added some extra checks in the past, but WIDOCO does not handle very well missing imports. Remove problematic imports and the ontology documentation will be generated properly.

When I attempt loading the ontology in WIDOCO, I get this error: 
00:13:00.591 [Thread-4] ERROR org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error1 for type Class
00:13:13.682 [Thread-4] ERROR org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error2 for type Class
00:13:27.745 [Thread-4] ERROR uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl - OWLOntologyManagerImpl.checkForOntologyIDChange() existing:Ontology(OntologyID(OntologyIRI(<http://www.w3.org/2004/02/skos/core>) VersionIRI(<null>))) [Axioms: 205 Logical Axioms: 42] First 20 axioms: {InverseObjectProperties(<http://www.w3.org/2004/02/skos/core#hasTopConcept> <http://www.w3.org/2004/02/skos/core#topConceptOf>) InverseObjectProperties(<http://www.w3.org/2004/02/skos/core#narrower> <http://www.w3.org/2004/02/skos/core#broader>) InverseObjectProperties(<http://www.w3.org/2004/02/skos/core#broadMatch> <http://www.w3.org/2004/02/skos/core#narrowMatch>) InverseObjectProperties(<http://www.w3.org/2004/02/skos/core#broaderTransitive> <http://www.w3.org/2004/02/skos/core#narrowerTransitive>) Declaration(AnnotationProperty(<http://www.w3.org/2004/02/skos/core#note>)) Declaration(Class(<http://www.w3.org/2004/02/skos/core#ConceptScheme>)) Declaration(AnnotationProperty(<http://www.w3.org/2004/02/skos/core#prefLabel>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#broadMatch>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#closeMatch>)) Declaration(Class(<http://www.w3.org/2004/02/skos/core#OrderedCollection>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#broaderTransitive>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#topConceptOf>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#semanticRelation>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#narrower>)) Declaration(DataProperty(<http://www.w3.org/2004/02/skos/core#notation>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#narrowerTransitive>)) Declaration(AnnotationProperty(<http://www.w3.org/2004/02/skos/core#historyNote>)) Declaration(AnnotationProperty(<http://www.w3.org/2004/02/skos/core#changeNote>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#exactMatch>)) Declaration(ObjectProperty(<http://www.w3.org/2004/02/skos/core#inScheme>)) }
00:13:27.753 [Thread-4] ERROR uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl - OWLOntologyManagerImpl.checkForOntologyIDChange() new:Ontology(OntologyID(Anonymous-452)) [Axioms: 0 Logical Axioms: 0] First 20 axioms: {}
Error while loading the ontology: Unknown ontology: OntologyID(OntologyIRI(<https://spec.edmcouncil.org/fibo/ontology/LOAN/LoanTypes/CommercialLoans/>) VersionIRI(<null>))

**Comment by dgarijo** [comment]
Since this seems to be an issue of the availability of the loaded ontology, I will close it. Please reopen if appropriate
