### ISSUE TITLE
Other sections are not included in the index file

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#260]
For the ontologies: 
https://github.com/ahmad88me/demo

used flags:
-rewriteAll  -ontFile
-outFolder -getOntologyMetadata
-saveConfig -htaccess

**Comment by dgarijo** [comment]
@ahmad88me,
the sections are produced and included.  You may be opening the html locally with chrome, which by default disables ajax loading. One of the ontologies was produced with errors, but that's another issue.
I will close this one

**Comment by ahmad88me** [comment]
I open it with firefox and it works fine. 👍
