### ISSUE TITLE
Missing JSONLD serialzation ?

### ISSUE THREAD

**Issue by landong1973** [dgarijo/Widoco#268]
Supported serialization formats were enabled in config.properties , e.g.
RDFXMLSerialization=ontology.xml
TurtleSerialization=ontology.ttl
N3Serialization=ontology.nt
JSONLDSerialization=ontology.json

However, following lines of hand-crafted serializations were found in CreateResource.java line 155, am I missing something?
WidocoUtils.writeModel(om, o, new RDFXMLDocumentFormat(), folderOut+File.separator+"ontology.xml");
WidocoUtils.writeModel(om, o, new TurtleDocumentFormat(), folderOut+File.separator+"ontology.ttl");
WidocoUtils.writeModel(om, o, new NTriplesDocumentFormat(), folderOut+File.separator+"ontology.nt");

should Jena be used to transform ontology to JSONLD?

https://github.com/avicomp/ont-api/wiki/Examples

 Model model = ((OntologyModel)ontology).asGraphModel();

**Comment by dgarijo** [comment]
At the moment I didn't add a JSON-LD serialization. It can easily be added in a future release. Nobody had requested it yet ;)
