### ISSUE TITLE
ANSI encoding of Java code?

### ISSUE THREAD

**Issue by landong1973** [dgarijo/Widoco#269]
As far as I know, all Java codes were ANSI encoded, which would cause compilation error in UTF-8 system.
Error: unmappable character for encoding UTF8 during maven compilation

Add following line into pom.xml would fix the problem.
<project.build.sourceEncoding>CP1252</project.build.sourceEncoding>

**Comment by dgarijo** [comment]
will do in the next release. Nobody has reported any problems when doing PRs, though

**Comment by dgarijo** [comment]
Fixed in https://github.com/dgarijo/Widoco/commit/b6c65ec50b94f641299f99547c988d018ac921e5
