### ISSUE TITLE
no main manifest attribute, in widoco-1.4.2.jar

### ISSUE THREAD

**Issue by timrdf** [dgarijo/Widoco#272]
I built widoco using `mvn package` to make 3 jars:

```
bash-3.2$ find . -name *.jar
./target/widoco-1.4.2.jar
./jar/widoco-1.4.2-jar-with-dependencies.jar
./jar/original-widoco-1.4.2-jar-with-dependencies.jar
```

I have a legit OWL file:

```
bash-3.2$ head source/representation.rdf 
<rdf:RDF xmlns="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:f="http://www.w3.org/2004/09/fresnel#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">

    <owl:Ontology rdf:about="http://www.w3.org/2004/09/fresnel">
        <dc:creator rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Chris Bizer &#60;chris@bizer.de&#62;</dc:creator>
        <dc:creator rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Emmanuel Pietriga &#60;emmanuel.pietriga@inria.fr&#62;</dc:creator>
```

I have the jar sitting in the current working directory to suit the command line usage in the README.md:

```
bash-3.2$ ls widoco-1.4.2.jar 
widoco-1.4.2.jar
```

But running a command following the README.md results in a jar execution issue:

```
bash-3.2$ java -jar widoco-1.4.2.jar -ontFile source/representation.rdf -outFolder manual/widoco -webVowl

no main manifest attribute, in widoco-1.4.2.jar
```

Switching to widoco-1.4.2-jar-with-dependencies.jar runs without the error shown for widoco-1.4.2.jar.

The README.md mentions `WIDOCO.jar` which isn't a thing.

**Comment by dgarijo** [comment]
I don't have this issue when I build the JAR. I will have to look into this. In the meantime, if you want to download it you can find it here: https://github.com/dgarijo/Widoco/releases/tag/v1.4.2

**Comment by dgarijo** [comment]
I have checked again and the pom.xml contains the main class:
<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
              <mainClass>widoco.gui.GuiController</mainClass>
            </transformer>
I cannot reproduce this issue :(

**Comment by timrdf** [comment]
@dgarijo Yes, the hiccup was the ambiguity from 3 jars and the mismatch in naming between the README.md and the actual jars generated. I'd suggest a note in the readme about the identity between `./jar/widoco-1.4.2-jar-with-dependencies.jar` and `WIKDOCO.jar` in the command line usage.
