### ISSUE TITLE
Application does not quite after generating the documentation

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#275]
After generating the documentation, the application does not quit. Which breaks the automated tests

**Comment by ahmad88me** [comment]
Invalid, it turned out that the application was not shutting down because of OOPS API. I got this message "Error while saving OOPS evaluation: Server returned HTTP response code: 502 for URL: http://oops-ws.oeg-upm.net/rest"

**Comment by dgarijo** [comment]
Got it! Thanks, Ahmad
