### ISSUE TITLE
handling text/URI/blank-node for dct:contributor and dct:creator

### ISSUE THREAD

**Issue by seralf** [dgarijo/Widoco#285]
Hi

I've experienced some issues with `dct:creator ` and `dct:contributors `.
Very often those properties are used with string literals containing the name of the person cited, so the HTML will contain those name.
But when a proper element with its own URI is used instead, the only metadata reported is simply its URI, while I suppose the best should be providing a `foaf:name` or similar, if present.

On the other hand, I see that ontology authors often use those properties with blank nodes and literals: even if this should be seen as a bad practice in general, it's widely used so I suppose it should be handled in some way.

Do you think this should be enhanced on LODE itself, or is it possible to fix it by widoco?

thanks in advance.

**Comment by dgarijo** [comment]
This is some of the extra handling I do in WIDOCO, because you can edit this information in the interface (LODE takes dct:creator as a literal only, if I am correct). However, at the moment if a URI is introduced as a dct:creator, I don't check whether it's an individual in the ontology or not. Also, I don't derreference the target URI, because very few vocabularies deal with that.

Doing everything automatically is a little tricky: there are many ways of specifying a creator (dc, schema, etc), plus the properties that could be used for name are also many as well. I will consider an extension in a future release, but at the moment I suggest adding literals/uris for this.

**Comment by seralf** [comment]
Hi thanks very much for the reply.

Just to expand the possibile examples: in our case, we have metadata in the following format:

```
<> a owl:Ontology ;
	dct:creator <http://some/ontology/people/somebody> ; 
	.
[...]
<http://some/ontology/people/somebody> foaf:Person ;
	foaf:name "John Smith"@en ;
	.
```

the individuals are materilized inside the vocabulary in order to avoid external dereferentiation. They should be available with a precise query, as well af if there were blank nodes (even if it's best to avoid blank nodes usage, anyway they are still widely used...).

Some heuristic may be used here for labels, looking at "common" properties like `foaf:name` in a certain order, maybe? I don't know how many cases there could be: I suppose starting from the 2-3 most used it may be simple to extend them later.


If it's possible to help in some way I could try add something by myself.

I look forward to see the enhancement, thanks very much!

**Comment by dgarijo** [comment]
Yes, so you have name individuals on the ontology, which is one of the ways of implementing this.
I will probably not tackle this issue in a while. If you want to contribute, you can look here: https://github.com/dgarijo/Widoco/blob/2e9ad1f79e510b535679fe71be6d94a9c029d4b2/src/main/java/widoco/Configuration.java#L501
That is the case where contributions are dealt with. At the moment if there is a URI, I just copy, ignoring whether it could be found in the ontology or not.
Thanks!

**Comment by GeorgFerdinandSchneider** [comment]
Hi @dgarijo !

thanks for the excellent work and capabilities on Widoco!

I also find the issue above difficult (Literals, URIs, BNodes) for the naming of creators.

In the linked [example](http://linked.earth/ontology/core/1.2.0/index-en.html) in the gallery I found that the creators are inserted in the ontology file with an IRI (e.g. http://orcid.org/0000-0001-5920-4751) and displayed as "Julien Emile-Geay". The Literal has been added manually, correct?

We recently had troubles with [foaf:name](https://github.com/w3c-lbd-cg/bot/issues/11), where FOAF:name is seen problematic anyway [LINK](https://mailman.stanford.edu/pipermail/p4-feedback/2011-July/004010.html). 

Is there any suggestions how to state creator in an ontology and anotate with email and name? I found the VCARD ontology, which seemed as a W3C standard suitable. Would the following be supported by Widoco (Display of Literal name and IRI as link, e.g. [Peter Smith](https://example.org/0000-1111-5555-4444)):

```turtle

<https://example.org/myfamousOntology> rdf:type owl:Ontology ;
  dcterms:creator <https://example.org/0000-1111-5555-4444> .

<https://example.org/0000-1111-5555-4444> rdf:type vcard:Individual, owl:NamedIndividual ;
  vcard:hasEmail mailto:MyEmail@example.org ;
  vcard:fn "Peter Smith" .
```

Thanks and BR

**Comment by dgarijo** [comment]
In the gallery the name of the authors and institutions were linked by hand, yes. Detecting automatically the name and institution is not currently supported by the tool, but I will try to have a look in the next release.

The problem too is that there are many ways of declaring the name/email. You can use rdfs:label for the name, you can use foaf:name, schema:name and schema:email... Or use vcard as you suggest. I will try to incorporate some of them but probably will miss many.

**Comment by GeorgFerdinandSchneider** [comment]
Fully agree, there is plenty, maybe too many, ways to do express this.

I was wondering if there is some "Best Practice", which could be agreed on among tools and services to limit the implementation effort. For instance the [best practices of LOV](https://lov.linkeddata.es/Recommendations_Vocabulary_Design.pdf) stipulate the use of [`dc:creator`](http://purl.org/dc/terms/creator) and an IRI of the person typed as `foaf:Person`.

Regarding LOV, potentially @mariapoveda can give some insights how the creator of an ontology artifact should be added at best? If this can be seen as some "standard" potentially this is a route to follow.

**Comment by dgarijo** [comment]
I created with @mariapoveda a best practice document for WIDOCO. If you see https://w3id.org/widoco/bestPractices#creators I list the properties that will be recognized by the tool. Right now the range can be a URI or a String, but I don't do any further processing in terms of URI.

I think that in the next iteration I will extend this so if the range is a URI, I will check for a few common properties (vcard, foaf, schema) and display the results.

**Comment by mariapoveda** [comment]
In LOV the dc:creator takes as object an URI identifying the creator. The way in which the creator is described (foaf, vcard...) is left to such URI providers.

**Comment by seralf** [comment]
I think using an URI is the most robust approach. However it's easy to
implement some heuristic  in order to retrieve the actual name: if the
given URI is a foaf:Person we can search for foaf:name, and so on... if any
standard ontology is used, we can also try with a standard rdfs:label or
similar...

what do you think about this?

Il giorno lun 15 giu 2020 alle ore 09:36 María <notifications@github.com>
ha scritto:

**Comment by dgarijo** [comment]
I will probably end up supporting both. Right now if you have a URI, it will work, but you will see the URI as author. In the next version I will query for rdfslabel/vcard:name/foaf:name/schema:givenName + family name to retrieve the info if existing. To keep things simple I won't try to resolve the URI though, it will be local to the ontology.

**Comment by seralf** [comment]
Then we have to suggest to the users to materialize all possibile authors
(and similar data) into the current ontology. De-referencig them could be
annoying indeed, anyway there are several cases where the author or
publisher or whatever will be remote by construction. A good compromise is
to suggest the materialization, I suppose, as a best practice: this way if
you avoid that, you can still expose the URI as you said. I would
recommend avoiding the idea of accept the usage of  author as a String
literal (that paradozically could be more easy to read, but actually
difficult to stadnardize).

Il giorno lun 15 giu 2020 alle ore 19:35 Daniel Garijo <
notifications@github.com> ha scritto:

**Comment by mariapoveda** [comment]
Actually in LOV it is also stored foaf:name and typed as foaf:Person. There are sameAs if more than one URI is provided.

https://lov.linkeddata.es/dataset/lov/sparql?query=PREFIX+vann%3A%3Chttp%3A%2F%2Fpurl.org%2Fvocab%2Fvann%2F%3E%0APREFIX+voaf%3A%3Chttp%3A%2F%2Fpurl.org%2Fvocommons%2Fvoaf%23%3E%0APREFIX+owl%3A%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+rdfs%3A%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0A%0A+%0A%23%23%23+Vocabularies+contained+in+LOV+and+their+prefix%0ASELECT+DISTINCT+%3Fe+%3Fp++%3Fo%0A%7B%0A+++++%3Fe+a++foaf%3APerson+.%0A++++%3Fe+%3Fp+%3Fo+.%0A%0A%7D

**Comment by dgarijo** [comment]
The easiest way is to have a string as the range of creator. 90% of the ontologies I have seen have it this way, and not handling this case would be wrong in my opinion. So I will continue to handle it. But I also believe I should handle the case where this is correctly done.

We can also update the Widoco guidelines to reflect this

**Comment by ldesousa** [comment]
@dgarijo I would consider using a string literal to identify the author of an ontology as a bad practice. There is no advantage in doing so and it breaks the linked data paradigm. Making detailed meta-data user friendly is one of the major advantages of a tool like Widoco.

I see the effort so far has been in supporting a wide range of meta-data ontologies. But as a user I would rather see few (even only one) supported, but in more detail. VCard is the canonical choice (with `Individual` and `Organisation`), but a bit intricate. Schema.org is less formal, but easier to use (with `Person` and `Organisation`). Then it is a mater of settling on a sub-set of properties to process, e.g. `name`, `address`, `email`, `URL`. Not many are necessary.

**Comment by dgarijo** [comment]
While in principle I agree with you, @ldesousa, most ontologies (I think even some of mine) use strings to assert authors. So instead of only supporting the right way, I would rather support all common practices :)
So far I have seen no one using vcard for defining authors.
