### ISSUE TITLE
typo in htaccess for json

### ISSUE THREAD

**Issue by dgarijo** [dgarijo/Widoco#286]
Should be 
RewriteCond %{HTTP_ACCEPT} application/ld\\+json
instead of
RewriteCond %{HTTP_ACCEPT} application/ld+json

**Comment by miranda-zhang** [comment]
I have some problems related to content negotiation using the generated `.htaccess`, apart from the missing escape for +
https://stackoverflow.com/questions/51959520/specify-and-test-htaccess-http-accept

**Comment by dgarijo** [comment]
Ok, I had a look at your file and posted an answer, it looks like it was a typo. I hope it helps!
