### ISSUE TITLE
Import section generates links for imports closure and not direct imports

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#294]
Widoco seems to be generating the imports closure for the ontology. Not sure if it can be restricted to the direct imports alone. That would be good to have. Else the documentation page seems to get cluttered.

**Comment by kartgk** [comment]
The imported ontologies section gets generated even without the ( -includeImportedOntologies ) flag. Is it possible to get rid of the 'imported ontologies' section from the index page

**Comment by dgarijo** [comment]
The -includeimportedOntologies refers to showing the terms of the imported ontologies in the documentation. It is true that this section will appear even if the ontology terms are not included. I will clarify this in the documentation, but I don't think it is desirable to take them out of the index page, as they are informative.

**Comment by kartgk** [comment]
Thanks for the response. Here is the problem that my associates are having. Take this example

https://spec.edmcouncil.org/fibo/widoco/master/2018Q2/BE/LegalEntities/CorporateBodies/index-en.html

The owl file

https://spec.edmcouncil.org/fibo/ontology/master/2018Q2/BE/LegalEntities/CorporateBodies/
[CorporateBodies.txt](https://github.com/dgarijo/Widoco/files/2220055/CorporateBodies.txt)

has only 10 imports and thats the exact set that we want to see on the page.

Instead we have 34 imports due to transitive imports.  Will it be possible to restrict only to direct imports.

**Comment by dgarijo** [comment]
Got it. I will work on it, but it will take some time. I am unavailable to work on this for the next couple of weeks.
