### ISSUE TITLE
Classes not shown in WebVowl - Can be invoked with parameters

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#296]
@dgarijo This is an enhancement request but could be a very small fix.

When we display ontology some classes dont get displayed. But there is a parameter that can be set  to make the degree of collapsing to 0, in which case all classes of the ontology will be displayed.

This can be done by setting the opts ,

http://visualdataweb.de/webvowl/#**opts=[doc=0]**

Can we make this the default through Widoco.  Else it is kind of non-trivial for users to search for their classes in the visualization interface.

**Comment by kartgk** [comment]
Just for reference, this is the information I got from webvowl team when I couldnt find my class (BranchOfGovernment) in the visualization

https://spec.edmcouncil.org/fibo/widoco/infra-276/latest/BE/Corporations/Corporations/index-en.html

https://github.com/VisualDataWeb/WebVOWL/issues/105

**Comment by dgarijo** [comment]
@kartgk,
I wouldn't want to make it default because big ontologies really would make the browser lag (or even crash)

However, I think that you raise a fair point. I will add another flag so this can be configured.

Thanks for reporting this!

**Comment by dgarijo** [comment]
I have been trying this but I am afraid it doesn't work properly. When I open the link: http://visualdataweb.de/webvowl/#opts=%5Bdoc=0;filter_disjoint=false;%5D#iri=https://github.com/VisualDataWeb/WebVOWL/files/1486657/GovernmentEntities_txt.txt 
I see the ontology collapsed in degree 8. Other options like hiding the side bar work, so maybe something has changed in the latest release. I will keep it as it is for now.

**Comment by dgarijo** [comment]
I will close this issue. Please reopen when the options for the doc work properly and I will add another flag. I have prepared widoco to add options in an easy manner.
