### ISSUE TITLE
Allow configuring which HTML fragments/sections to generate (or not) when producing documentation

### ISSUE THREAD

**Issue by ocorcho** [dgarijo/Widoco#297]
As Widoco is integrated in Ontoology, which automatically generates a pull request with all the documentation generated by Widoco after submitting a new version of an ontology in a GitHub repository, we have detected that a nice feature would be to be able to configure Widoco with the HTML fragments/sections to generate (and not to generate), from the set of HTML files that are being generated by default.

As a example, an ontology developer may be working on an ontology in a GitHub repository, connected to Ontoology. Once the first version of the documentation is generated, the ontology developer will probably start working on the introduction section, on the overall description of the classes, properties, etc. It would be nice not to regenerate those sections with empty placeholders, but maintaining the previous version edited by the ontology developer.

**Comment by dgarijo** [comment]
This is already supported. As in the documentation:

The -crossRef option will ONLY generate the overview and cross reference sections. The index document will NOT be generated. The htaccess, provenance page, etc., will not be generated unless requested by other flags. This flag in intended to be used only after a first version of the documentation exists.

**Comment by dgarijo** [comment]
I will close the issue. Please reopen if you consider the above is not enough
