### ISSUE TITLE
new language with cross reference

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#298]
Hola Dani, 
 If I already generated the documentation in English and then added a new language (e.g Spanish), the documentation will not be generated for the Spanish language if I run it with cross reference. Below I have the command and the options I used.

1. This does not generate the documentation for Spanish and Italian
```java -jar  -Dfile.encoding=utf-8 /home/vagrant/widoco/widoco.jar  -rewriteAll  -ontFile '/home/vagrant/repos/test/alo.owl' -outFolder '/home/vagrant/repos/test/OnToology/alo.owl/documentation' -getOntologyMetadata  -htaccess -lang en-es-it```

2. This does generate the documentation for all, but will over right the documentation (I think).
```java -jar  -Dfile.encoding=utf-8 /home/vagrant/widoco/widoco.jar  -rewriteAll  -ontFile '/home/vagrant/repos/test/alo.owl' -outFolder '/home/vagrant/repos/test/OnToology/alo.owl/documentation' -confFile /home/vagrant/repos/test/OnToology/alo.owl/documentation/alo.owl.widoco.conf -crossRef -htaccess -lang en-es-it```

Cheers,

**Comment by dgarijo** [comment]
@ahmad88me,
I cannot reproduce these errors:

java -jar -Dfile.encoding=utf-8 widoco-1.4.4-jar-with-dependencies.jar -ontURI https://raw.githubusercontent.com/ahmad88me/demo/master/alo.owl# -outFolder doc -includeImportedOntologies -webVowl -lang en-es-fr

produces the documentation for all three languages.

java -jar -Dfile.encoding=utf-8 widoco-1.4.4-jar-with-dependencies.jar -ontURI https://raw.githubusercontent.com/ahmad88me/demo/master/alo.owl# -outFolder doc -includeImportedOntologies -webVowl -lang en-es-pt -crossRef

produces only the overview and crossref section of the ontology

will generate the ontology properly. 

Note that italian is not supported.

**Comment by dgarijo** [comment]
Also, every language has its own label (abstract-en.html, abstract-es.html, etc.) so no general documentation is overwritten.

**Comment by ahmad88me** [comment]
(venv) vagrant@vagrant-ubuntu-trusty-64:~$ java -jar -Dfile.encoding=utf-8 ~/widoco/widoco.jar  -ontFile '/home/vagrant/repos/ahmad/alo.owl'  -includeImportedOntologies -webVowl -lang en-es-pt -crossRef -outFolder ~/test/


--WIzard for DOCumenting Ontologies (WIDOCO).
 https://w3id.org/widoco/

Command -ontFile not recognized.
Usage: java -jar widoco.jar [-ontFile file] or [-ontURI uri] [-outFolder folderName] [-confFile propertiesFile] [-getOntologyMetadata] [-oops] [-rewriteAll] [-crossRef] [-saveConfig configOutFile] [-lang lang1-lang2] [-includeImportedOntologies] [-htaccess] [-licensius] [-webVowl] [-ignoreIndividuals] [-includeAnnotationProperties] [-analytics analyticsCode]

**Comment by dgarijo** [comment]
Still cannot reproduce issue. See below:
java -jar -Dfile.encoding=utf-8 widoco-1.4.5-jar-with-dependencies.jar -ontFile testOntos/alo.owl -outFolder doc -includeImportedOntologies -webVowl -lang en-it-pt  -htaccess -rewriteAll

Everything was produced correctly. I don't understand why you are getting this error if previously the option was working. Nothing has changed.

**Comment by dgarijo** [comment]
Also tried this on another computer, other OS. Couldn't reproduce the issue. It looks like the error may be on your end...
