### ISSUE TITLE
Consider publishing Widoco to Maven Central

### ISSUE THREAD

**Issue by Nyamiou** [dgarijo/Widoco#301]
Hi,

I'm trying to run this site generation as part of a Maven build, in order to directly add the documentation to the generated Maven site. One issue I have with this is that Widoco is not in Maven Central which force me to have the JAR on my project or use download-maven-plugin, both solutions are not great in a corporate setting. So could you please consider submitting the project to Maven Central ?

Thanks.

**Comment by dgarijo** [comment]
Sounds good, I will have a look at this, but it will probably take some time.

**Comment by Nyamiou** [comment]
Thank you. No problem, I'll wait.

**Comment by seralf** [comment]
Hi that would be nice!

here it is a good guide: https://medium.com/@scottyab/how-to-publish-your-open-source-library-to-maven-central-5178d9579c5

meanwhile, in order to use widoco as a dependency with maven, it's possible (as sugested in the guide) to use [jitpack](https://jitpack.io/): https://jitpack.io/#dgarijo/Widoco/v1.4.9 using the code:

```xml
<dependencies>
  <dependency>
      <groupId>com.github.dgarijo</groupId>
      <artifactId>Widoco</artifactId>
      <version>v1.4.9</version>
  </dependency>
</dependencies>
[ ... ]
<repositories>
	<repository>
	    <id>jitpack.io</id>
	    <url>https://jitpack.io</url>
	</repository>
</repositories>
```

**Comment by dgarijo** [comment]
Thanks, @seralf !

**Comment by mthl** [comment]
Also Github provides some features for publishing Java packages when doing a release https://help.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-maven

**Comment by dgarijo** [comment]
I will try to look this up for the next release.

**Comment by dgarijo** [comment]
After giving this some thought, I have seen that the path of least resistance is adopt the approach proposed by @seralf. Everything is already done!: https://jitpack.io/#dgarijo/Widoco
I will update the documentation in the readme to clarify how to import WIDOCO from there easily.

**Comment by dgarijo** [comment]
I updated the readme file. Please let me know if this is not enough for importing WIDOCO.

**Comment by mthl** [comment]
Thanks for thinking about it,

I am currently using this solution but with the latest release (v1.4.13) I ended up having issues regarding dependencies being downloaded over HTTP instead of HTTPS which is subject to man of the middle attacks.

```
Retrieving org/springframework/boot/spring-boot-dependencies/1.5.6.RELEASE/spring-boot-dependencies-1.5.6.RELEASE.pom from central
Tried to use insecure HTTP repository without TLS:
 maven-restlet: http://maven.restlet.org
 com/fasterxml/jackson/jackson-bom/2.8.9/jackson-bom-2.8.9.pom 
 
This is almost certainly a mistake; for details see 
https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md
```

To work around that issue I ended up overriding the repository URL to force HTTPS

```clj
  :repositories [["jitpack" "https://jitpack.io"]
                 ["spring-ext" "https://repo.spring.io/ext-release-local/"]
                 ["spring-milestones" "https://repo.spring.io/milestone"]
                 ["spring-snapshots" "https://repo.spring.io/snapshot"]
                 ["maven-restlet" "https://maven.restlet.org"]]
```

**Comment by dgarijo** [comment]
Thanks for the info! I am going to remove additional dependencies in the next release (Jena is not used, and has many dependencies). Hopefully that will help addressing the issue

**Comment by dgarijo** [comment]
I removed some unused dependencies and repositories. Hopefully that made things better.
