### ISSUE TITLE
Support for converting JSON-LD ontologies

### ISSUE THREAD

**Issue by soderluk** [dgarijo/Widoco#302]
This is more of a question, than an issue: We have defined our ontology in a JSON-LD document, which we would like to be able to automatically generate to a HTML page. This tool would be ideal for the task, but according to https://github.com/dgarijo/Widoco/blob/master/src/main/java/widoco/Constants.java#L43 only RDF, Turtle and N3 are supported.
Do you have any thoughts about implementing JSON-LD processing as well?

**Comment by dgarijo** [comment]
I am about to do another release fixing a few bugs,  so if you send me a link to your ontology in JSON then I will be happy to include it.

**Comment by soderluk** [comment]
I'm not sure I follow; what do you mean by including our ontology?
It's still in draft stages, so the URL will not be the final at this point in time.

**Comment by dgarijo** [comment]
I meant to include the feature, testing it out with your ontology. Unfortunately I am not aware of many ontologies published in JSON. I will try converting one.

**Comment by soderluk** [comment]
OK! I'll give you the link to the ontology I used as preference https://www.w3.org/ns/hydra/core
This one will include the information needed. Thank you in advance!

**Comment by dgarijo** [comment]
Hmm, I cannot get that JSON to load by the OWL API. There is little else I can do here (it tells me that "Not a valid (absolute) IRI: @context").  I cannot load the ontology in Protege either.

However, I generated an ontology in JSON and loaded it successfully, so I'll close this issue in the next release.

Rather than waiting for the APIs to be in place, I would suggest to provide another serialization in case the JSON one does not work. For example, when I try to resolve hydra I see they provide Turtle and I can generate the documentation easily.

**Comment by soderluk** [comment]
JSON-LD is an extension for JSON, which adds support for linked data structures. I think that the library would need separate support for handling JSON-LD.
I can of course first convert the JSON-LD structure to RDF, and from there build the HTML-pages, but it would've been great if the library could support the JSON-LD transformation as well.

Further information about JSON-LD is found at https://json-ld.org/ if you're interested in finding out more.

**Comment by dgarijo** [comment]
I am familiar with JSON-LD :)

WIDOCO uses the OWL API, which has support for JSON-LD ontologies. However, the ontology you sent me doesn't seem to load. Maybe the OWL API (I am using version 5.1.0) is not there. I will try to upgrade the API. I have tested saving an ontology as JSON-LD and then loading it again. And it works properly.

I am not going to re-implement a JSON-LD parser, as it would be reinventing the wheel.

**Comment by dgarijo** [comment]
This is an example of a JSON ontology now supported by WIDOCO:
[ontology.json.txt](https://github.com/dgarijo/Widoco/files/2345141/ontology.json.txt)

**Comment by soderluk** [comment]
Yeah, OK, I had a misunderstanding there :)
Great if we get this to work, so there's no need to convert back and forth between JSON-LD and RDF. Thanks for your fast responses!

**Comment by dgarijo** [comment]
No problem! The next release might take a little bit because I am working on a tutorial too. It will come later this week. Thanks for your feedback!
