### ISSUE TITLE
WebVOWL 404 Error

### ISSUE THREAD

**Issue by megankatsumi** [dgarijo/Widoco#307]
Hello,
When I generate the documentation the WebVOWL visualization returns a 404 error. However, when I test the ontology (both the URL and the file that I am using with widoco to generate the html documentation) with the online version of WebVOWL, the visualization is generated with no issues. Any thoughts on what might be going wrong?

Thank you!
Megan

**Comment by dgarijo** [comment]
Hello,
I can't reproduce the issue with the ontologies I have.  Please provide a link to your ontology so I can test this out. I integrated the version 1.12 of WebVowl in the last release, so if anything works on their page it should also work with WIDOCO (in theory)

**Comment by megankatsumi** [comment]
Hello,
Here is a link to the ontology: http://w3id.org/icity/Activity/
I've encountered the same error with others as well. If it helps, I encountered this error when I updated to the last release.

**Comment by dgarijo** [comment]
@megankatsumi,
thanks! Now I have been able to reproduce it. 
The problem was that I was using an old version of owl2vowl. I have fixed it. 
This issue will be solved in the next release.

**Comment by megankatsumi** [comment]
Great! Looking forward to it.
