### ISSUE TITLE
Could not find artifact AbsoluteLayout

### ISSUE THREAD

**Issue by Nyamiou** [dgarijo/Widoco#309]
Trying to build locally or with JitPack (https://jitpack.io/#dgarijo/Widoco), I get the error:

Could not find artifact unknown.binary:AbsoluteLayout:jar:SNAPSHOT

Isn't this supposed to be:

      <dependency>
          <groupId>org.netbeans.external</groupId>
          <artifactId>AbsoluteLayout</artifactId>
          <version>RELEASE802</version>
      </dependency>

From the Netbeans repository:

    <repository>
        <id>netbeans</id>
        <name>Netbeans repository</name>
        <url>http://bits.netbeans.org/maven2/</url>
    </repository>

**Comment by dgarijo** [comment]
I am using an old version of netbeans, so this is possible.
I suggest you remove the dependency and class from your local copy (they do not affect the main functionality of the tool). I will check this out when I have the time.

**Comment by dgarijo** [comment]
I just removed the dependency. Hopefully it will work now (I will release the code very soon)

**Comment by dgarijo** [comment]
See https://jitpack.io/#dgarijo/Widoco :)
