### ISSUE TITLE
dcterms:publisher not recognised

### ISSUE THREAD

**Issue by xgfd** [dgarijo/Widoco#311]
I have the following triples in my ontology. The title is recognised by widoco 1.4.6 but not the publisher, as shown in the screenshot.
<http://companydomain.co.uk/ontologies/risk> rdf:type owl:Ontology ;
                                                       <http://purl.org/dc/terms/title> "Risk Ontology"@en ;
                                                       <http://purl.org/dc/terms/publisher> "Company Name @2018"@en .

![image](https://user-images.githubusercontent.com/4529752/46284491-ec38fe80-c56f-11e8-8e39-6bb829951793.png)

**Comment by dgarijo** [comment]
Hmmm, this should be recognized. I will test this out.

**Comment by xgfd** [comment]
It seemed that the publisher was picked up in the generated web page.

**Comment by dgarijo** [comment]
Yes, the problem is that in the interface it's expecting a publisher URL instead of a name. I have fixed this now and will be pushed in the next release
