### ISSUE TITLE
owl:equivalentClass choose which to be indexable

### ISSUE THREAD

**Issue by miranda-zhang** [dgarijo/Widoco#312]
I have a calss definition
```
###  https://w3id.org/cocoon/v1.0#UnitOfMeasure
cocoon:UnitOfMeasure rdf:type owl:Class ;
          owl:equivalentClass qudt:Unit .
```
In the generated document, it has the enty for
[qudt:Unit](https://miranda-zhang.github.io/cloud-computing-schema/v1.0/index-en.html#http://qudt.org/schema/qudt#Unit)
But I want an enty for "cocoon:UnitOfMeasure" with a clickable hash url to it.

**Comment by miranda-zhang** [comment]
Related to 
https://github.com/dgarijo/Widoco/issues/208
Adding annotations would solve the issue.

**Comment by dgarijo** [comment]
@miranda-zhang,
glad you could solve it? Do you think we need to add something in the documentation to clarify this?

**Comment by miranda-zhang** [comment]
Having a few sentences in the doc would be good.

**Comment by dgarijo** [comment]
Can you explain the problem a little further? I don't understand it very well.
Thanks in advance

**Comment by miranda-zhang** [comment]
It's actually the same thing as https://github.com/dgarijo/Widoco/issues/208
Widoco does not generate the class `cocoon:UnitOfMeasure` if I only have
`cocoon:UnitOfMeasure rdf:type owl:Class  .`

Adding an annotation, i.e., `rdfs:comment "UnitOfMeasure defines custom units."@en` would make it appear.
