### ISSUE TITLE
Add link to JSON-LD context in config

### ISSUE THREAD

**Issue by tarjelavik** [dgarijo/Widoco#313]
It would be nice to be able to add a url to a jsonld context in the config. Is this something that could be added?

**Comment by dgarijo** [comment]
Hi @tarjelavik,
could you please give an example on how would this would work? I don't understand very well what would you expect WIDOCO to generate.
If you are interested in generating the JSON-LD context, perhaps OnToology (http://ontoology.linkeddata.es/) may be more appropriate?

**Comment by tarjelavik** [comment]
Hi @dgarijo! Sorry for the short description. 

In my build script for my [ontology](https://momayo.gitlab.io/onto-momayo/), I use https://github.com/stain/owl2jsonld to generate my JSON-LD context. I was wondering if could be useful to add the possibility in `config.properties` to set the URL to the context? Then it could be picked up and used in `index.html`.

```yaml
...
thisVersionURI=http://purl.org/net/p-plan
contextURI=http://purl.org/net/p-plan/context
...
```
At the moment I have manually added the context URL to the generated `index.html`, seen here: https://momayo.gitlab.io/onto-momayo/

**Comment by dgarijo** [comment]
Oh I see. Thanks! 
Should be doable then. 
Daniel

**Comment by tarjelavik** [comment]
Great! And thanks for Widoco! 😄
