### ISSUE TITLE
Spanish version of HTML documentation generates wrong text in table of contents

### ISSUE THREAD

**Issue by ocorcho** [dgarijo/Widoco#316]
The table of contents in the Spanish version of the HTML documentation generates and additional "volver al índice" text in the link text.
You can check it at http://vocab.linkeddata.es/datosabiertos/def/comercio/tejido-comercial/index-es.html (just generated with Ontoology, so probably with an earlier version of Widoco).

**Comment by dgarijo** [comment]
The table is automatically generated, so this means I probably did a mistake in the translation that affects the html. I will look into this
