### ISSUE TITLE
Editing Imported Ontologies

### ISSUE THREAD

**Issue by iesnaola** [dgarijo/Widoco#317]
Hi,

This is a minor issue, but it could be taken into consideration for future versions of WIDOCO.

In the 2nd step of WIDOCO (where you load the metadata), the "Imported Ontologies" option launches the following window. I think the "Extended Ontology Name" and "Extended Ontology URI" titles should be replaced by "Imported Ontology Name" and "Imported Ontology URI". In fact, there is a "Extended Ontologies" option, so I guess these titles come from this tab.

![image](https://user-images.githubusercontent.com/25657162/48189939-a1b25b00-e341-11e8-89af-964d09e6ac0f.png)

Best regards,
Iker

**Comment by dgarijo** [comment]
Hello,
They are not the same. Extended ontologies are those for which you use or
extend a class or two but do not directly import. Imported ontologies have
the owl:imports statement. Imported ontologies are automatically detected,
but extended ones are not. I will have to review the form anyway, as it is
misleading as it stands. Thanks!

**Comment by iesnaola** [comment]
Hi,

Sorry for the reply, but I think I didn't explain myself correctly in the previous message. Or maybe I didn't understand you.

I know there are two different "Extended ontologies" and "Imported ontologies". However, the headers in these two, are the same "Extended Ontology Name" and "Extended Ontology URI". I think "Imported ontologies" tab's headers should have "Imported" instead of "Extended". Otherwise it can be a little confusing.

![image](https://user-images.githubusercontent.com/25657162/48248663-90785580-e3f8-11e8-8907-7a0157ee4f50.png)
![image](https://user-images.githubusercontent.com/25657162/48248918-7c812380-e3f9-11e8-88c7-77186ec58078.png)
![image](https://user-images.githubusercontent.com/25657162/48248936-8dca3000-e3f9-11e8-9c6e-28a63440385d.png)

**Comment by dgarijo** [comment]
Yes, you are correct! Thanks for spotting this!
