### ISSUE TITLE
Add support for Jena's ont-policy.rdf file to resolve imports with local files

### ISSUE THREAD

**Issue by jgeluk** [dgarijo/Widoco#327]
For giant "ontology families" like FIBO we have many imports per ontology (especially if you look at the full imports closure). Currently widoco uses OWLAPI which tries to resolve these imports by using an HTTP GET request to get them. This is not only very slow but sometimes incorrect since the local version of any given import might be newer than the remote version.
For FIBO we already generate the ont-policy.rdf file (see https://jena.apache.org/documentation/ontology/#document-manager-policy) so we would like Widoco to detect that file and use it when it's there. This would not require any additional configuration on the command line.

**Comment by dgarijo** [comment]
I believe this issue has been fixed by the latest merge
