### ISSUE TITLE
Documentation is not Generated

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#333]
Documentation is not generated for this ontology. Here is the command I used:
`java -jar  -Dfile.encoding=utf-8 /widoco/widoco.jar  -rewriteAll  -ontFile '/ontology/respond_0_4.owl' -outFolder '/OnToology/ontology/respond_0_4.owl/documentation' -getOntologyMetadata  -licensius  -saveConfig /OnToology/ontology/respond_0_4.owl/documentation/respond_0_4.owl.widoco.conf -htaccess -lang en`

The ontology is here: `https://github.com/ahmad88me/RESPOND-Ontology/tree/master/ontology`

I am using: widoco-1.4.9

**Comment by ahmad88me** [comment]
I also face the same problem with widoco-1.4.8. But it to work with 1.4.7

**Comment by dgarijo** [comment]
The issue is due to a bad import: https://w3id.org/bot/0.3.0. Remove bad import and problem is gone.

**Comment by dgarijo** [comment]
@ahmad88me I am going to make the next version of WIDOCO to fail silently when there are errors in imports.

**Comment by ahmad88me** [comment]
Thanks 👍
