### ISSUE TITLE
Improve log messages during error exception

### ISSUE THREAD

**Issue by jgeluk** [dgarijo/Widoco#335]
At the moment we're getting useless error messages like:

```
13:55:08 INFO  CreateResources      :: - ontology IRI: https://spec.edmcouncil.org/fibo/ontology/CIV/Funds/CIV/
Parsing Complete!
Error while generating the documentation in is null
```
Some error messages are printed to the system console and some to the logger, everything should go via the logger so that we can configure what's being shown and what isn't.

And the error message `Error while generating the documentation in is null` doesn't help so we need more info.

**Comment by dgarijo** [comment]
Logging has been improved, but I will double check this for the next release. if you have some sample tests it would be great
