### ISSUE TITLE
replace System.err.println() to logger.error()

### ISSUE THREAD

**Issue by seralf** [dgarijo/Widoco#342]
Hi using the jar from code as a dependency, it would be very helpful to replace `System.err.println()` to `logger.error()`, in order to enable a standard external custom configuration, from slf4j (which is already used).

Some of the traced exceptions are logger to the standard error log console, but not propagated externally, for example:

```java
private void loadPropertyFile(String path){
  ...
  } catch (Exception ex) {
    System.err.println("Error while reading configuration properties "+ex.getMessage());
  }
}
```
[source](https://github.com/dgarijo/Widoco/blob/master/src/main/java/widoco/Configuration.java#L360-L362)

In this case, when we call a `new Configuration()`:

```java
public Configuration() {
  ...
  propertyFile = new Properties();
  ...
  try{
    ...
    loadPropertyFile(path + File.separator + Constants.CONFIG_PATH);
  } catch (URISyntaxException e) { 
    // NOTE: this block is unreachable if the exceptions in loadPropertyFile are not propagated! 
    logger.error("Error while loading the default property file: " + e.getMessage());
  }
}
```

we will not get its own error message, but the logging stopped inside `loadPropertyFile()` method.

For example I'd suggest to change the `loadPropertyFile` to something like:

```java
private final org.slf4j.Logger logger = LoggerFactory.getLogger(this.getClass());
...
private void loadPropertyFile(String path) throws IOException {
  try {
  ...
  } catch (IOException ex) {
      logger.error("Error while reading configuration properties " + ex.getMessage());
      throw ex;
  }
}
```

this way it's possible to manage an exception strategy into the public methods later in the chain (for example `reloadProperties()`) without affecting the other ones.

This may help with issues #252 #277 and #335

**Comment by dgarijo** [comment]
I think this is mostly addressed in the last release, where I migrated all logs to sfl4j (the one owlapi uses), so we didn't have conflicts with log4j. I will double check for the next release whether all errors are properly logged.

**Comment by dgarijo** [comment]
I believe all the logging is captured now correctly
