### ISSUE TITLE
Widoco finishes with error

### ISSUE THREAD

**Issue by OrangieLou** [dgarijo/Widoco#346]
Hi,
sorry if this is the wrong place to ask this question but I am really excited to try your program:
Unfortunately I can't seem to make it work. I downloaded the latest jar with dependencies, followed your tutorial and tried some simple owl files and some from your test folder. But whatever I do when I click *Generate* in step 3 the program always finishes with *An error occurred while generating the documentation. Please check that the ontology opens with Protege and that there are not empty metadata fields*. 
I kept all default check boxes and tried it with and without a config file. All the owl files work fine in Protege. Am I doing anything wrong or missing something obvious?

**Comment by dgarijo** [comment]
hello,
it is impossible for me to reproduce this issue if you don't specify which of the ontologies produce an error. The test ontologies should not produce one, I have tested the tool in many different computers and OS, successfully, so I am not sure what could be your problem. 
Do you have Java 8 installed? It's the only dependency required.

**Comment by OrangieLou** [comment]
I'm using ubuntu 16.04 and this is the output I get running java -version:

java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

I used the examples coil.owl and otalex.owl.

**Comment by OrangieLou** [comment]
I think I managed it know. I ran the program via command line and it seems to work perfectly now. Before I just double clicked the jar to start the program. Maybe there is something off with java access from nautilus or I don't know. Sorry for bothering! Maybe you can add that to the tutorial that running via command line might be the better option. :)

**Comment by dgarijo** [comment]
Glad you figured it out. This is weird, as the only dependency for WIDOCO is Java 8, and I have tested it in unix machines in the past. In fact, I mostly use the graphical UI. 
Can you please run the UI through the command line and post here the log error? You just have to run it with no parameters.

**Comment by OrangieLou** [comment]
I ran widoco in Downloads folder with your test file coil.owl and kept the default. It works fine. This was the output:

java -jar widoco-1.4.10-jar-with-dependencies.jar

Error while reading configuration properties /home/lamlou/Downloads/config/config.properties (No such file or directory)


--WIzard for DOCumenting Ontologies (WIDOCO).
 https://w3id.org/widoco/


You are launching WIDOCO GUI


To use WIDOCO through the command line please do:

java -jar widoco.jar [-ontFile file] or [-ontURI uri] [-outFolder folderName] [-confFile propertiesFile] [-getOntologyMetadata] [-oops] [-rewriteAll] [-crossRef] [-saveConfig configOutFile] [-lang lang1-lang2] [-includeImportedOntologies] [-htaccess] [-licensius] [-webVowl] [-ignoreIndividuals] [-includeAnnotationProperties] [-analytics analyticsCode] [-doNotDisplaySerializations] [-displayDirectImportsOnly][-rewriteBase rewriteBasePath]. 
See more information in https://github.com/dgarijo/Widoco/#how-to-use-widoco

You chose to save this file: coil.owl
log4j:WARN No appenders could be found for logger (widoco.WidocoUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Annotation(<http://purl.org/dc/terms/bibliographicCitation> "An ontology for videogame interoperability. Parkkila, J.; Radulovic, F.; Garijo, D.; Poveda-Villalón, M.; Ikonen, J.; Porras, J.; and Gómez-Pérez, A. Multimedia Tools and Applications"@en)
Annotation(<http://purl.org/dc/terms/contributor> <http://delicias.dia.fi.upm.es/members/DGarijo/#me>)
Annotation(<http://purl.org/dc/terms/created> "02-13-2015"^^xsd:date)
Annotation(<http://purl.org/dc/terms/creator> <http://www.mendeley.com/profiles/janne-parkkila/>)
Annotation(<http://purl.org/dc/terms/description> "Extension of the video game ontology to represent the main concepts of the game Coil"@en)
Annotation(<http://purl.org/dc/terms/license> <http://creativecommons.org/licenses/by-nc-sa/2.0/>)
Annotation(<http://purl.org/dc/terms/title> "Coil Videogame Ontology"@en)
Annotation(<http://purl.org/ontology/bibo/doi> "10.1007/s11042-016-3552-6"@en)
Annotation(<http://purl.org/vocab/vann/preferredNamespacePrefix> "coil"^^xsd:string)
Annotation(<http://purl.org/vocab/vann/preferredNamespaceUri> <https://w3id.org/games/spec/coil#>)
Annotation(rdfs:comment "Extension of the video game ontology to represent the main concepts of the game Coil"@en)
Annotation(rdfs:label "Coil Ontology"@en)
Annotation(owl:versionInfo "1.0"^^xsd:decimal)
Ontology loaded successfully
Parsing Complete!
No previous version provided. No changelog produced!
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Doc successfully generated for lang en

**Comment by dgarijo** [comment]
Yes, this is the output of a normal run. I was asking for the log of the error you found with the GUI ;)

**Comment by OrangieLou** [comment]
sorry, then I'm a bit lost on how to do this. The error appears only when I double click the jar without using the command line. How do I get the log when I don't use the command line? It works if I start the GUI via command line but not if I start the GUI via double click on the jar.

**Comment by dgarijo** [comment]
If you run the GUI through the command line (i.e., you do java -jar widoco.jar without the arguments). Then when the GUI disappears due to the error, you will see the error in the command line

**Comment by OrangieLou** [comment]
> If you run the GUI through the command line (i.e., you do java -jar widoco.jar without the arguments). 

That works, that is no problem. The problem only occurs when I double click the jar without using the command line at all.

> Then when the GUI disappears due to the error, you will see the error in the command line

It actually doesn't disappear. It opens pop up window which says _An error occurred while generating the documentation. Please check that the ontology opens with Protege and that there are not empty metadata fields._
When I close the pop up I can start over again from the beginning (only to end up with the same error in the pop up in the end again).

**Comment by rrovetto** [comment]
I also got the error "An error occurred while generating the documentation. Please check that the ontology opens with Protege and that there are not empty metadata fields." but not with with other owl files. Windows 10, java 8. I tried both command prompt and standard desktop interface. What could it be?

**Comment by dgarijo** [comment]
@rrovetto without knowing which ontology you are trying to open, there is little I can do.
It may be that you are importing ontologies that don't resolve.

**Comment by rrovetto** [comment]
locally-stored owl files. what are specific possible reasons one file might work, but not another? 
For example, the error says "that there are not empty metadata fields."--what does that refer to?

**Comment by dgarijo** [comment]
Without seeing the ontology it is nearly impossible for me to tell you about the error. 
It may not work because you are trying to import files in your owl file that are making the OWL API fail (WIDOCO uses the same one as Protege). But I can't say more without seeing the ontology. Empty metadata fields usually refer to properties that may have no annotation values or empty ones. If you upload the ontology somewhere I can dig in

**Comment by rrovetto** [comment]
after testing owl files that work with it, this is what happens: whenever a new annotation property is added to a file, the error pops up for that file; and when that property is removed the error no longer appears.

**Comment by dgarijo** [comment]
Please provide an example OWL file. Otherwise I cannot reproduce the issue.

**Comment by abhilashcb8** [comment]
@dgarijo : Respected sir, I am trying to use the tool. but I am getting the following error message on click of generate button "
"An error occured whil egenerating the documentation. Please check that the ontology opens with protege and that are not empty metadata fields" 
Guess some issue with my own system. Is there any alternate i can go with.
I have attached the required info for your reference. 
![x1911Mq17e](https://user-images.githubusercontent.com/50736052/121811800-1892fb80-cc83-11eb-9afa-5d4203ebe166.png)

With regards the data annotation - I have added the annotation for classed and object properties along with data properties. 
even then I ended with the same issue. 
Please guide me in this sir. 
Thank you.

**Comment by dgarijo** [comment]
@abhilashcb8 usually people open a new issue, but that's ok.
Can you run Widoco through the console (open a terminal and do java -jar widoco...jar) and then post here the error that is shown?
As I mentioned to you, I was able to run widoco fine with your ontology. See the result attached. Note that you'll have to upload it to a server in order to visualize it properly
[myDocumentation.zip](https://github.com/dgarijo/Widoco/files/6644081/myDocumentation.zip)

**Comment by abhilashcb8** [comment]
I tried with the console but getting the error as shown below.
![image](https://user-images.githubusercontent.com/50736052/121816503-ac6fc200-cc99-11eb-91aa-97a8899f4fb8.png)

I changed the system as well but still not able to rectify it.

**Comment by abhilashcb8** [comment]
Sir it worked when I used the console. 
Sorry for your time.
Thanks. but the documentation looks empty. After I generated the document, I opened it with the web browser but its showing empty.

**Comment by abhilashcb8** [comment]
Sir, it worked and I am able to generate the documentation.

Thanks a lot, sir.

![image](https://user-images.githubusercontent.com/50736052/121816976-59e3d500-cc9c-11eb-98a6-651cd57c265f.png)

**Comment by dgarijo** [comment]
Glad you could solve your issues, @abhilashcb8.
Please see https://github.com/dgarijo/Widoco#browser-issues-why-cant-i-see-the-generated-documentation--visualization if your documentation appears empty. In short, it's a browser issue that disappears when hosting the html in a server
