### ISSUE TITLE
Widoco Workflow

### ISSUE THREAD

**Issue by fkleedorfer** [dgarijo/Widoco#349]
I would like to use the Widoco CLI in recurring publishing workflows. This is currently not easy, as there is no way to fully specify all resources needed for a build. The suggested workflow seems to be
1. Finish editing ontology (forever)
2. Generate documentation using widoco
2. Edit the generated documentation until happy
3. Publish

However, if the ontology is still under development, it may change, and with it, some of the description/introduction/abstract text may, too.

Therefore, I would prefer this workflow:
1. Edit ontology
2. Edit some markdown files that will be picked up by widoco CLI
3. Maybe update some images (also being picked up by widoco CLI)
4. Generate documentation using widoco 

Currently I'm scripting that. The approach is that for an ontology file (the authoritative version is TTL, in my case), there may be a folder. If there is one, each of the following files therein are also optional:
* `widoco.conf` file
* `abstract-[lang].md`
* `introduction-[lang].md`
* `overview-[lang].md`
* `description-[lang].md`
* `references-[lang].md`
* `img` folder with images referenced from the markdown files.
After running widoco (with the `-confFile` option if there is a `widoco.conf` file in the folder): 
* the content of the `<span class="markdown">[...]</span>` element in the each `sections/*.html` file is replaced with the content of the respective markdown file in this folder. Thus, one can suppress custom text in that section by supplying an empty markdown file.
* the `img` folder is copied to the `outFolder` such that it is on the same level as the `sections` folder

My suggestion would be to add an option `-configDir <configDir>` that allows for specifying such a directory.

**Comment by dgarijo** [comment]
This is supported by running the -crossref option:

> The -crossRef option will ONLY generate the overview and cross reference sections. The index document will NOT be generated. The htaccess, provenance page, etc., will not be generated unless requested by other flags. This flag in intended to be used only after a first version of the documentation exists.

This way you may configure the rest of the sections the way you prefer, and WIDOCO will not touch them. Since you are not working on a new version, the index.html will not change either. We have been using this option to support cases such as the one you refer.
