### ISSUE TITLE
References html overwrites overview section

### ISSUE THREAD

**Issue by OrangieLou** [dgarijo/Widoco#350]
Hi,
I tried to include references as a section and it always substitutes the overview section and not the references. I had a quick look at the source code and it looks like a copy-paste mistake in CreateResources.java in line 284 where it says "overview-". But you know your code better, so you might wanna take a look. ;)
Thanks.

**Comment by dgarijo** [comment]
Good catch! Yep, this seems to be an error. I will check it out.
