### ISSUE TITLE
Placing imported/referenced classes in a different section of the documentation

### ISSUE THREAD

**Issue by ocorcho** [dgarijo/Widoco#352]
When classes or properties are reused from other ontologies (e.g., typical case when one creates SKOS concepts or concept schemes, or some schema.org classes or properties), the documentation in sections 4.1, 4.2 and 4.3 include also those ontology components, as if they were in the ontology that is being developed.

It may be nice to have them in a different section: imported/reused ontology components, or to place them where they are in a different colour (greyed) or alike.

If this is not possible, it should be possible to specify which ones to avoid generating documentation for or documenting differently in the Widoco configuration file.

**Comment by dgarijo** [comment]
The flag `includeImportedOntologies` seems to do that:

> The -includeImportedOntologies flag indicates whether the terms of the imported ontologies of the current ontology should be documented as well or not.

Note that if the current ontology extends the properties (i.e., they have been manually added in the ontology), then they will be part of the documentation. For example, if your class "Dataset" extends "schema:Dataset", then the latter will appear as a class.

Does this address your issue?

**Comment by dgarijo** [comment]
I will close this issue, I opener #389 to deal with the distinction part.
