### ISSUE TITLE
Is License rendering (using Licensius.com) intended to be working?!

### ISSUE THREAD

**Issue by pmcb55** [dgarijo/Widoco#356]
I really like the idea of using Licensius to fetch a link, name and logo for the actual software license in use. But it seems the code is currently disabled from doing so (i.e. 'Class GetLicense' doesn't seem to be used at all from the current code.

Is this becuase Licensius is not reliable, or not being maintained? I had trouible with it trying to lookup the simple MIT license (which I think should be 'http://rdflicense.appspot.com/rdflicense/MIT1.0', although that doesn't seem to support content negotiation, so using 'http://rdflicense.appspot.com/rdflicense/MIT1.0.ttl' seems to get useful Turtle back). Or should the URI be 'http://purl.org/NET/rdflicense/MIT1.0.ttl' (which seems slightly better, as it's a PURL address)?

Anyway, I'm just trying to understand your current thinking on retrieving and displaying license information in Widoco?

**Comment by dgarijo** [comment]
Since Licensius had some hiccups in their service stability, I added it under demand. There is a button in the UI for connecting; and an option in command line to retrieve from it. Las time I tried it was used in the application.

**Comment by dgarijo** [comment]
Since this is not really an issue but a question, I will close it. Please reopen it if appropriate. Licensius is used in WIDOCO to retrieve license URL and name, but only on demand via the "use Licensius WS" on the UI or the "-licensius" flag.
