### ISSUE TITLE
URL fragments don't work (most of the time)

### ISSUE THREAD

**Issue by tkuhn** [dgarijo/Widoco#361]
The URL fragments for jumping to specific sections in the document don't seem to work for me, for example: https://peta-pico.github.io/FAIR-nanopubs/principles/index-en.html#https://w3id.org/fair/principles/terms/F1

Sometimes it works, but mostly not. I am assuming this is due to the fact that the content is dynamically loaded. Depending on how quickly the browser loads the page and executes the JavaScript, the fragment works or not.

**Comment by dgarijo** [comment]
Unless you have a very big file there is usually not a problem: most of the cross section is loaded in a single fragment. The alternative would be to have a single HTML, but that is inconvenient if you just want to comment out certain parts. Do you know of another workaround? Maybe moving to the anchor after all javascript has loaded?

**Comment by tkuhn** [comment]
The file I link above is not very big at all, and still it exhibits the problem I reported (often not on the first try but afterwards, probably due to speedup from caching).

I would prefer a single HTML file, but I understand that there are other use cases where this might lead to other problems.

Putting the code to move to the anchor later in the code might indeed solve it, if my understanding of the problem is correct.

**Comment by tkuhn** [comment]
ps: tested on Firefox and Chrome (Ubuntu).

**Comment by tkuhn** [comment]
This doesn't seem to solve the problem for me. I recreated the documents with the latest version, but it still often doesn't work...

**Comment by dgarijo** [comment]
@tkuhn,
did you use the "-uniteSections" flag? It includes everything in a single html file, which should address the problem. By default, this flag will not be used, because I didn't want to change the default behavior of the tool

**Comment by tkuhn** [comment]
No I didn't. That explains it :)

I just re-created the document with the "-uniteSections" flag and indeed it solves the problem. This is great. Thank you so much!

**Comment by dgarijo** [comment]
Nice!
