### ISSUE TITLE
License 404 badge not found

### ISSUE THREAD

**Issue by kmcglinn** [dgarijo/Widoco#369]
Hi There,

When I add a license tag to my ontology, WIDICO generates a "License 404 badge not found" - https://www.scss.tcd.ie/~mcglink/ontologies/geoff/index-en.html

What is the recommended way to represent the license correctly?

Kris.

**Comment by dgarijo** [comment]
@kmcglinn,
Widoco expects the license to be a URL. The badge errors happens because  you added a paragraph, which creates an error when retrieving an image for it.

**Comment by dgarijo** [comment]
You can add text, but I believe you will have to edit that field in your html for the time being. Apologies

**Comment by kmcglinn** [comment]
Thanks Daniel,

I had missed the link for the image. 

Best,

Kris.

**Comment by dgarijo** [comment]
Since this seems to be resolved, I will close this issue. Please reopen if appropriate
