### ISSUE TITLE
Generating provenance-en.ttl using config.properties file leads to unvalid turtle file

### ISSUE THREAD

**Issue by HaydarAk** [dgarijo/Widoco#373]
Using the widoco.jar with -confFile' parameter and a config.properties file leads to an unvalid provenance-en.ttl turtle file. If I enter an author / contributor to the config.properties file: 
`authors=John Doe`
`contributors=Jane Doe`

widoco generates a provenance-en.ttl with following lines:
```
dc:title "someTitle";
prov:wasAttributedTo :agent0;
prov:wasAttributedTo :agent1;

:agent0 a prov:Agent; foaf:name "John Doe".
:agent1 a prov:Agent; foaf:name "Jane Doe".
```
In my understanding, there should be an underscore **_** before :agent0/agent1 to be valid blank nodes, like this:
```
prov:wasAttributedTo _:agent0;
...
_:agent0 a prov:Agent; foaf:name "John Doe".
```
Otherwise, it is not a valid turtle. 

Tested with [Online RDF/Turtle validators](http://ttl.summerofcode.be/) as well as the [raptor-2  validator](https://packages.debian.org/en/sid/raptor2-utils)

**Comment by dgarijo** [comment]
Thanks, I will have a look. I think I didn't declare a local namespace
