### ISSUE TITLE
Contributors metadata 

### ISSUE THREAD

**Issue by iesnaola** [dgarijo/Widoco#377]
Hi,

I was looking at the guidelines you proposed, and I saw something that might be a mistake. In section **3.5.2 Contributors** the properties that might be used refer to _dcterms:creator_ and _dc:creator_, although I think they should be _dcterms:contributor_ and _dc:contributor_ instead.

Please, check it.

**Comment by dgarijo** [comment]
You are right. I fixed it. Thanks!
