### ISSUE TITLE
Why are some namespaces splitted ?

### ISSUE THREAD

**Issue by tfrancart** [dgarijo/Widoco#383]
Why am I getting this ? see the namespace "05", corresponding to a split of the "skos-xl" namespace :

![image](https://user-images.githubusercontent.com/2728945/79310009-84e96200-7efb-11ea-977e-97a7d9838e72.png)

I expect the namespace "05" to disappear.
My config is :

```
importedOntologyNames=SKOS core;SKOS-XL
importedOntologyURIs=http://www.w3.org/2004/02/skos/core;http://www.w3.org/2008/05/skos-xl
extendedOntologyNames=
extendedOntologyURIs=
```

Thanks !

**Comment by dgarijo** [comment]
This part is extracted from LODE and the OWL API when parsing the ontology. You are not doing anything wrong, it's just that this part has not received much attention so far. As a quick fix you can edit the HTML being produced.

**Comment by dgarijo** [comment]
I have dug into this and fixed it (not pushed it yet). When importing skos, this are the ns that will appear:
```
dct-http://purl.org/dc/terms/
owl-http://www.w3.org/2002/07/owl#
rdf-http://www.w3.org/1999/02/22-rdf-syntax-ns#
xml-http://www.w3.org/XML/1998/namespace
xsd-http://www.w3.org/2001/XMLSchema#
rdfs-http://www.w3.org/2000/01/rdf-schema#
skos-http://www.w3.org/2004/02/skos/core#
skos-xl-http://www.w3.org/2008/05/skos-xl#
```

**Comment by dgarijo** [comment]
Fixed in develop branch
