### ISSUE TITLE
uniteSections didn't work

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#385]
The command I used:
`java -jar  -Dfile.encoding=utf-8 widoco/widoco.jar  -rewriteAll  -ontFile 'alo.owl' -outFolder 'documentation' -confFile documentation/alo.owl.widoco.conf -crossRef -htaccess  -webVowl -lang en-es-fr -uniteSections`

**Comment by dgarijo** [comment]
I will have to test this out.. what was the result? Can you attach the configuration file and ontology? Thanks!

**Comment by ahmad88me** [comment]
Sure, (here)[https://github.com/ahmad88me/demo/tree/master/OnToology/alo.owl/documentation]
and (ontology)[https://github.com/ahmad88me/demo/blob/master/alo.owl]
Thanks :)

**Comment by dgarijo** [comment]
I have checked this out. The flags you used are incompatible. On the one hand, you use the "uniteSections" flag, which tells WIDOCO to write everything on the index.html. On the other hand, you use the "crossRef" flag, which does NOT produce an index.html. Hence, the index.html is not generated. Drop the crossRef command and this will be fixed, but the documentation will be overwritten.

WIDOCO does not support rewriting the crossRef only section when the rest of the sections are in the same document (I will open an issue to do this).
