### ISSUE TITLE
Is it supposed to work with RDFS ontologies?

### ISSUE THREAD

**Issue by ColinMaudry** [dgarijo/Widoco#386]
Hello there,

I have an ontology that only uses RDFS terms, not OWL.

Is WIDOCO supposed to work with these? Because beside the header and the Acknowledgements section, the generated HTML is blank.

If it's not WIDOCO's scope, can you recommend a tool?

**Comment by dgarijo** [comment]
Have you seen: https://github.com/dgarijo/Widoco#browser-issues-why-cant-i-see-the-generated-documentation--visualization?

Do the "sections" folder contain html? If so, everything worked. Browsers block loading these files locally but it will work correctly if you put your documentation on a server.

Or if you use the `-uniteSections` flag, you should be able to see the results.

If you still experience issues after this, please reopen this issue and provide a pointer to the ontology you are trying to load.

**Comment by ColinMaudry** [comment]
Hello !

My bad, I found so many tools that didn't work with RDFS that I gave up a bit early :)

Thanks!

**Comment by dgarijo** [comment]
No worries, I will try to clarify this more in the documentation or find another workaround. It is annoying that you cannot see the documentation locally :(
Thanks!
