### ISSUE TITLE
Specifying custom settings for WebVOWL

### ISSUE THREAD

**Issue by ColinMaudry** [dgarijo/Widoco#390]
Hi!

My instance is here: https://vocab.sireneld.io/sirene/webvowl/index.html#

I would like to customise the default WebVOWL settings, mainly:

- degree of collapsing 0
- max label length 200

I saw that these settings can be specified in the VOWL json that the app exports. It's explained on the (thin) [WebVOWL official documentation](http://vowl.visualdataweb.org/webvowl.html#linking):

> Alternatively, the generated JSON file can be exported and linked or uploaded. If the JSON file has been exported using WebVOWL, the VOWL visualization will be restored with the layout and user settings it had before.

I have edited the generated `webvowl/data/ontology.json` and added a valid `settings` object (inspired from the [sample JSON](http://vowl.visualdataweb.org/webvowl/foaf.json)) that sets two settings to non-default values (freshly generated, it doesn't have a `.settings`):

```json
{
  "settings": {
    "filter": {
      "degreesSliderValue": "0"
    },
    "gravity": {
      "datatypeDistance": 450
    }
  }
}
```

But that doesn't affect the display configuration when I open WebVOWL.

Questions:

- is `webvowl/data/ontology.json` loaded by the generated WebVOWL instance?
- can you think of a way to edit the settings?

I almost opened this issue in the WebVOWL repo, but I first need to understand how Widoco set it up.

Thanks!

**Comment by ColinMaudry** [comment]
I also try adding a fully filled `settings` object (not just the settings I wanted to edit) and edit it. No success either.

**Comment by dgarijo** [comment]
Hi @ColinMaudry,
yes, WIDOCO will generated tha ontology.json through owl2vowl and then load it up.  If you modify that file, then it should work appropriately. If it doesn't then it could be because I have a previous version of WebVOWL in WIDOCO which doesn't support this behavior...

**Comment by dgarijo** [comment]
Fixed in `develop` branch. I tested it out, it was just an issue of updating to a newer WebVowl version.
