### ISSUE TITLE
Display all user-generated annotations

### ISSUE THREAD

**Issue by rrovetto** [dgarijo/Widoco#391]
Please add the functionality allowing WIDOCO to automatically recognize and display user-generated metadata or annotations. Currently it only recognizes a set of annotations from rdfs, dc, etc. 
For example, in addition to dc:description, allow WIDOCO to automatically display/render user-generated annotations such as something like 'definition', etc.
I believe this will be helpful to all users. Thank you.

**Comment by dgarijo** [comment]
@rrovetto these are all the properties recognized by WIDOCO: https://w3id.org/widoco/bestPractices
Definition is redered from rdfs:comment (or several others options).  Is this not enough? I will close the issue because this functionality is there, please reopen if you mean something else
