### ISSUE TITLE
Add a description about markdown in class description

### ISSUE THREAD

**Issue by dgarijo** [dgarijo/Widoco#404]
It's there but it's buried. Should show an example in the gallery

**Comment by pipauwel** [comment]
2-1.2esw

-------- Oorspronkelijk bericht --------
Van: Daniel Garijo <notifications@github.com>
Datum: 6/06/2020 01:39 (GMT+01:00)
Aan: dgarijo/Widoco <Widoco@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Onderwerp: [dgarijo/Widoco] Add a description about mearkdown in class description (#404)


It's there but it's buried. Should show an example in the gallery

—
You are receiving this becaus😅😊e you are subscribed to this thread.

**Comment by dgarijo** [comment]
??

**Comment by pipauwel** [comment]
Sorry, pocket dial - ignore and erase please

**Comment by dgarijo** [comment]
Fixed in https://github.com/dgarijo/Widoco/commit/5bc73e7bc716ae729c3bef29308dc1f9699ee5e9
