### ISSUE TITLE
Publish annotation properties

### ISSUE THREAD

**Issue by Serge3006** [dgarijo/Widoco#406]
Hi, there is a way for Widoco to also describe the annotation properties defined in my ontology?

Thanks.

**Comment by dgarijo** [comment]
Right now custom annotation properties are not supported, sorry. You would have to change the xslt from LODE to add your custom variables. If some of them are common among ontologies, you can open a feature request and I can try to generalize.

**Comment by dgarijo** [comment]
@Serge3006,
reviewing this issue I realize that I may have misinterpreted your question.

You can include the annotation properties defined in your ontology, you just have to select the option:

![image](https://user-images.githubusercontent.com/1520666/88135280-8336d680-cb9b-11ea-912c-340e57ae729b.png)

**Comment by Serge3006** [comment]
Perfect, that is what I was looking for, thank you :)

**Comment by dgarijo** [comment]
All right, closing issue then
