### ISSUE TITLE
Ontology contributors do not appear in html documentation

### ISSUE THREAD

**Issue by ednaru** [dgarijo/Widoco#426]
Original contributors that had initially been added with dc:contributor appeared in the generated html documentation under "Contributors". Added a couple of new contributors and regenerated the documentation, these new contributors do not appear in the html.

**Comment by dgarijo** [comment]
I tried this, and it worked correctly.
I think it's an issue with OnToology: if an initial index document exists, it won't be regenerated. Hence, I am closing this issue here.
