### ISSUE TITLE
Titles in Spanish are rewritten

### ISSUE THREAD

**Issue by ednaru** [dgarijo/Widoco#427]
When having html documentation in Spanish and English, and we regenerate documentation due to some change, section titles in the Spanish html documentation are rewritten by Widoco to the English ontology title.

**Comment by dgarijo** [comment]
Hi Edna,
I don't understand how to reproduce this issue. Each document is generated
separately every time...
Best,
Daniel

**Comment by ednaru** [comment]
Hi Dani.
I generated documentation with Ontoology for the "Convenios" vocabulary:
https://github.com/CiudadesAbiertas/vocab-sector-publico-convenios

I rewrote correctly the tiles by editing directly the html. If you  
want to try it out, you can change the ontology and see what happens  
with the Spanish documentation when Widoco generates the documentation.

Best regards,

Edna
Quoting Daniel Garijo <notifications@github.com>:

**Comment by dgarijo** [comment]
Hi Edna,
what I mean is that I don't understand the steps that you take in order to reproduce the issue. You first generate the documentation in spanish, and then in english in another file? Do you use the GUI or the CLI? etc.

**Comment by ednaru** [comment]
Hi Dani. I use Widoco through Ontoology and it generates the two sets of documentation in one run.
Edna 

Enviado desde mi iPhone

**Comment by dgarijo** [comment]
Ok, then there is a possibility that this is an OnToology issue as well. I will try to reproduce it and let you know the result.

**Comment by dgarijo** [comment]
I tried reproducing this issue in Widoco, and I can't. It may be an issue related to Ontoology. Pinging @ahmad88me

**Comment by ahmad88me** [comment]
@ednaru  There is a chance that this was solved with the new version of OnToology. Let me know if the problem persists so I can look further into it from OnToology side. 
Best,
