### ISSUE TITLE
List of namespaces is not generated correctly in the documentation

### ISSUE THREAD

**Issue by ednaru** [dgarijo/Widoco#428]
We understand that the list of namespaces should be generated correctly from the prefixes in the ontology. However, this is not occurring. For our docmentation we have edited the namespaces directly in the html. For example in:
https://github.com/opencitydata/hacienda-presupuesto

You can see that the prefixes in the ontology are:
<rdf:RDF xmlns="http://vocab.ciudadesabiertas.es/def/hacienda/presupuesto#"
     xml:base="http://vocab.ciudadesabiertas.es/def/hacienda/presupuesto"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:ns="http://www.w3.org/2003/06/sw-vocab-status/ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:skos="http://www.w3.org/2004/02/skos/core#"
     xmlns:time="http://www.w3.org/2006/time#"
     xmlns:skos1="http://www.w3.org/2008/05/skos#"
     xmlns:terms="http://purl.org/dc/terms/"
     xmlns:espresup="http://vocab.ciudadesabiertas.es/def/hacienda/presupuesto#">

The namespaces generated in the documentation are:

espresup | <http://vocab.ciudadesabiertas.es/def/hacienda/presupuesto>
-- | --
owl | <http://www.w3.org/2002/07/owl>
xsd | <http://www.w3.org/2001/XMLSchema>
skos | <http://www.w3.org/2004/02/skos/core>
rdfs | <http://www.w3.org/2000/01/rdf-schema>
esadm | <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio>
rdf | <http://www.w3.org/1999/02/22-rdf-syntax-ns>
terms | <http://purl.org/dc/terms>
time | <http://www.w3.org/2006/time>
dc | <http://purl.org/dc/elements/1.1>

**Comment by dgarijo** [comment]
This issue is similar to others regarding namespaces. I plan to rework this part and allow previsualizing it in the UI. I will work on this whenever I have the time

**Comment by dgarijo** [comment]
Fixed in develop branch.
