### ISSUE TITLE
[Documentation] Specify which metadata properties from the ontology are used and where

### ISSUE THREAD

**Issue by Zack-83** [dgarijo/Widoco#436]
Lo primero, muchas gracias por desarrollar este programa muy útil que nos simplifica la vida 👍 

**Describe the bug**
Widoco does not propagate all ontology metadata into the HTML documentation, although written according to the good practice documents.
They are not propagated into the `config` file either.
On the other way, for some fields there is no way to generate them from the ontology source file - it works only from the `config` file (authorsInstitution, authorsURI) or not at all (introduction).

**Expected behavior**
The metadata should be reported into the HTML output.
It should be clear which metadata field in the ontology corresponds to which position in the output and to which row in the `config` file. Either should this full information be reported in the metadata best practices document, or an inverse export function (config --> ttl) should be offered.

**Screenshots**
Input:
```ttl
<https://www.metadata4ing.org> rdf:type owl:Ontology ;
                               vann:preferredNamespaceUri "https://nfdi4ing.de/metadata4ing#" ;
                               vann:preferredNamespacePrefix "m4i" ;
                               dcterms:title "Metadata4Ing: An ontology for describing the generation of research data within a scientific activity."@en ;
                               dcterms:description "Metadata4Ing is the metadata schema of NFDI4Ing ."@en ;
                               dcterms:abstract "blablablablablablablablablablabla." ;
                               rdfs:comment "Que barba" ;
                               skos:note "doremifasol" ;
                               bibo:status "draft" ;
                               owl:versionIRI "1.0.0" ;
                               owl:versionInfo "v1.0.0" ;
                               dcterms:replaces "v0.0.0" ;
                               dcterms:created "2020-11-09" ;
                               dcterms:creator "Sancho Panza" ;
                               dcterms:license "The license will be open and specified at a later time."@en .
```
Output:
![grafik](https://user-images.githubusercontent.com/37865804/98534814-552ded00-2285-11eb-98b5-73f9bb7eb56a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 64 bit
 - Browser: Firefox 82.0.2, 64 bit
 - Widoco-Version: 1.4.13

**Comment by dgarijo** [comment]
@Zack-83,
thanks for your feedback. You seem to be using different metadata properties that capture the same value (note, description, comment); so WIDOCO only displays one of them. All other properties (except replaces, which I am not sure it's implemented) should be in the html one way or the other. 

What seems to be the error in particular? You are posting a snapshot, but leaving to interpretation what you think it may be off.

**Comment by Zack-83** [comment]
@dgarijo ,
thanks for replying so fast!
I would like to have a transparent overview of which metadata fields are converted between ontology preamble, `config.properties` file and output document. With trials and errors, I got the following table:

| HTML output                      | `config.properties` fields | Good practices document                       | Ontology metadata                                                            | Range            | Remarks                                        |
| -------------------------------- | -------------------------- | --------------------------------------------- | ---------------------------------------------------------------------------- | ---------------- | ---------------------------------------------- |
| _(referred to in the document)_  | ontologyName               | 3.1.1. Vocabulary namespace URI [RECOMMENDED] | vann:preferredNamespaceUri                                                   | Literal or URI ? | see boldface remark in Good practices document |
| _(referred to in the document)_  | ontologyPrefix             | 3.1.2. Prefix [RECOMMENDED]                   | vann:preferredNamespacePrefix                                                | xsd:string       |                                                |
| _title_                          | ontologyTitle              | 3.2.1. Title [RECOMMENDED]                    | dc:title dcterms:title schema:name                                           | xsd:string       |                                                |
| **Abstract**                     | abstract                   | 3.2.3. Abstract [OPTIONAL]                    | dc:abstract dcterms:abstract                                                 | xsd:string       |                                                |
| **Revision:**                    | ontologyRevisionNumber     | 3.3.2. Version info [RECOMMENDED]             | owl:versionInfo schema:schemaVersion                                         | xsd:string       |                                                |
| **Previous version:**            | previousVersionURI         | 3.4.1. Previuos version [RECOMMENDED]         | owl:priorVersion pav:previousVersion dcterms:replaces prov:wasRevisionOf     | URI ?            |                                                |
| **Release**                      | dateOfRelease              | 3.4.3. Modification date [OPTIONAL]           | dcterms:modified schema:dateModified                                         | xsd:dateTime     |                                                |
| **Authors:**                     | authors                    | 3.5.1. Creators [RECOMMENDED]                 | dcterms:creator dc:creator schema:creator pav:createdBy prov:wasAttributedTo | xsd:string       |                                                |
| **Contributors:**                | contributors               | 3.5.2. Contributors [RECOMMENDED]             | dcterms:contributor dc:contributor schema:contributor pav:contributedBy      | xsd:string       |                                                |
| **Publisher:**                   | publisher                  | 3.5.3. Publisher [OPTIONAL]                   | dcterms:publisher dc:publisher schema:publisher                              | xsd:string       |                                                |
| **DOI:**                         | DOI                        | 3.6.1. DOI [OPTIONAL]                         | bibo:doi                                                                     | URI ?            |                                                |
| **Cite as:**                     | citeAs                     | 3.6.2. Bibliographic citation [OPTIONAL]      | dcterms:bibliographicCitation schema:citation                                | xsd:string       |                                                |
| **License:**                     | licenseName                | 3.7. Vocabulary license [RECOMMENDED]         | dc:rights dcterms:license schema:license cc:license                          | Literal or URI ? |                                                |
| **Compatible with:**             | backwardsCompatibleWith    | 3.3.3. Backward compatibility [OPTIONAL]      | owl:backwardCompatibleWith                                                   | URI ?            |                                                |
| **Incompatible with:**           | ???                        | 3.3.4. Incompatibility [OPTIONAL]             | owl:incompatibleWith                                                         | URI ?            | missing in config.properties                   |
| **Visualization:**               | ---(automatic)             | ---                                           | ---                                                                          | ---              |                                                |
| **Provenance of this page**      | ---(automatic)             | ---                                           | ---                                                                          | ---              |                                                |
| **Table of contents**            | ---(automatic)             | ---                                           | ---                                                                          | ---              |                                                |
| **2. Overview**                  | ---(automatic)             | ---                                           | ---                                                                          | ---              |                                                |
| **4. Cross reference for [...]** | ---(automatic)             | ---                                           | ---                                                                          | ---              |                                                |
| **6. Acknowledgements**          | ---(automatic)             | ---                                           | ---                                                                          | ---              | personalisation wished                         |
| ???                              | ???                        | 3.2.2. Description [RECOMMENDED]              | dc:description dcterms:description rdfs:comment schema:description skos:note | xsd:string       | not possible to propagate                      |
| ???                              | status                     | 3.2.4. Status [OPTIONAL]                      | bibo:status                                                                  | xsd:string       | not possible to propagate                      |
| ???                              | ???                        | 3.3.1. Version IRI [RECOMMENDED]              | owl:versionIRI schema:schemaVersion                                          | URI ?            | not possible to propagate                      |
| ???                              | ???                        | 3.4.2. Creation date [RECOMMENDED]            | dcterms:created schema:dateCreated prov:generatedAtTime pav:createdOn        | xsd:dateTime     | not possible to propagate                      |
| ???                              | ???                        | 3.4.4. Issued date [OPTIONAL]                 | dcterms:issued schema:dateIssued                                             | xsd:dateTime     | not possible to propagate                      |
| ???                              | ???                        | 3.4.5. Source [OPTIONAL]                      | dc:source dcterms:source prov:hadPrimarySource                               | URI ?            | not possible to propagate                      |
| ???                              | ???                        | 3.8.1. Vocabulary logo [OPTIONAL]             | foaf:logo schema:logo                                                        | URI ?            | not possible to propagate                      |
| ???                              | ???                        | 3.8.2. Vocabulary diagram [OPTIONAL]          | foaf:depiction schema:image                                                  | URI ?            | not possible to propagate                      |
| ???                              | ???                        | 3.9. Similar resources [OPTIONAL]             | rdfs:seeAlso                                                                 | URI ?            | not possible to propagate                      |
| **This version:**                | thisVersionURI             | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| **Latest version:**              | latestVersionURI           | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| _Authors ID_                     | authorsURI                 | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| _Authors affiliation_            | authorsInstitution         | ???                                           | ???                                                                          | xsd:string       | not possible to express in source ontology     |
| _Authors affiliation ID_         | authorsInstitutionURI      | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| _Contributors ID_                | contributorsURI            | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| _Contributors affiliation_       | contributorsInstitution    | ???                                           | ???                                                                          | xsd:string       | not possible to express in source ontology     |
| _Contributors affiliation ID_    | contributorsInstitutionURI | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| _Publisher ID_                   | publisher URI              | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| _Publisher affiliation_          | publisherInstitution       | ???                                           | ???                                                                          | xsd:string       | not possible to express in source ontology     |
| _Publisher affiliation ID_       | publisherInstitutionURI    | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| **Imported Ontologies:**         | importedOntologyNames      | ???                                           | ???                                                                          | xsd:string       | not possible to express in source ontology     |
| _Importes ontologies URI_        | importedOntologyURIs       | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| **Extended Ontologies:**         | extendedOntologyNames      | ???                                           | ???                                                                          | xsd:string       | not possible to express in source ontology     |
| _Extended ontologies URI_        | extendedOntologyURIs       | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| **Download serialization:**      | RDFXMLSerialization etc.   | ???                                           | ???                                                                          | xsd:string       | not possible to express in source ontology     |
| _License URI_                    | licenseURI                 | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| _License badge_                  | licenseIconURL             | ???                                           | ???                                                                          | URI              | not possible to express in source ontology     |
| **1. Introduction**              | ???                        | ???                                           | ???                                                                          | ???              | not possible to express in source ontology     |
| **3. Description**               | ???                        | ???                                           | ???                                                                          | ???              | not possible to express in source ontology     |
| **5. References**                | ???                        | ???                                           | ???                                                                          | ???              | not possible to express in source ontology     |
|                                  |                            |                                               |                                                                              |                  |                                                |

**Comment by dgarijo** [comment]
Thanks, I think this is useful

There are a few things that we do (e.g., authors id comes from dc:creator if they added a URI instead of string, same with license/or by using the licensius service). Imported ontologies are taken from owl:import. There may be others, but I have to review.

**Comment by Zack-83** [comment]
Many thanks. Here is an equivalent form of the table. (MD is not accepted by GitHub as attachment; instead XLSX or DOCX or HTML would.)
[Widoco-Metadaten.xlsx](https://github.com/dgarijo/Widoco/files/5522488/Widoco-Metadaten.xlsx)

**Comment by muenchhausen** [comment]
How to complete the list? Do I understand this correctly, today, the file `extraction.xsl' seems to be the central source of information.

e.g. abstract section is fed by `rdfs:comment`: 
```xml
   <xsl:template match="rdfs:comment[f:isInLanguage(.)]" mode="ontology">
        <h2>
            <xsl:value-of select="f:getDescriptionLabel('abstract')"/>
        </h2>
        <xsl:call-template name="get.content"/>
    </xsl:template>
```

e.g. introduction section is somehow differently fed by `dc:description`:
```xml
    <xsl:template match="dc:description[f:isInLanguage(.)][normalize-space() != '']" mode="ontology">
        <h2 id="introduction">
            <xsl:value-of select="f:getDescriptionLabel('introduction')"/>
        </h2>
        <xsl:call-template name="get.content"/>
    </xsl:template>
```

**Comment by dgarijo** [comment]
@muenchhausen,
the extraction.xsl does not perform the metadata extraction, I separated this in another process for convenience so some of the metadata fields could be loaded from a custom configuration, or through the UI as well. 

I am going to address this issue in the next release, because I want to be a little more explicit in the guidelines. I hope to get some free time and work on this very soon.

**Comment by dgarijo** [comment]
Push to `develop` branch, will be addressed in next release once I completely align Widoco with the tables. See https://github.com/dgarijo/Widoco/blob/develop/doc/metadataGuide/guide.md#onto for an overview on how this looks now.

**Comment by Zack-83** [comment]
Very well! I'm looking forward to the next release.
