### ISSUE TITLE
OOPS evaluation report cannot be hosted on Linux due to case sensitivity

### ISSUE THREAD

**Issue by tjroamer** [dgarijo/Widoco#455]
Due to case-insenstivity of Windows, the OOPS page cannot be hosted on a Linux server. I looked into the generated index.html, and found the following line:

```html
<dt>Evaluation:</dt><dd><a href="OOPSEvaluation/OOPSeval.html#" target="_blank"><img src="https://img.shields.io/badge/Evaluate_with-OOPS! (OntOlogy Pitfall Scanner!)-blue.svg" alt="Evaluate with OOPS!" /></a></dd><dt>Cite as:</dt>
```

However, the generated folder has a name `OOPSevaluation` and the HTML file has a name `oopsEval.html`. On Windows, the link works just fine, but if the generated files are hosted on a Linux server, the link will fail with 404.

A simple fix would be: change the cases in the `index.html` to match exactly the folder and file names:

```html
<dt>Evaluation:</dt><dd><a href="OOPSevaluation/oopsEval.html#" target="_blank"><img src="https://img.shields.io/badge/Evaluate_with-OOPS! (OntOlogy Pitfall Scanner!)-blue.svg" alt="Evaluate with OOPS!" /></a></dd><dt>Cite as:</dt>
```

This way, the link would work on both Windows and Linux.

**Comment by dgarijo** [comment]
Nice catch @tjroamer 
I will do a release this week (I hope) fixing this among other things.
