### ISSUE TITLE
Error when generating file

### ISSUE THREAD

**Issue by LiniXiang** [dgarijo/Widoco#459]
**Describe the bug**
I followed the widoco tutorial, but failed at the last step "Generate File". The software reported an error saying "An error occurred while generating the documentation. Please check that the ontology opens with Protege and that there are not empty metadata fields". I am puzzled because:

1. I opened the protege, and the original ontology.
2. I tried to fill all metadata/some metadata/none metadata, and the error persisted.

Please give me some guidance, thanks!
**Screenshots**
![捕获](https://user-images.githubusercontent.com/80392788/122508335-69fd0b00-d034-11eb-8497-a1d0832378d3.PNG)

**Desktop (please complete the following information):**
 - OS: win10, x64
 - Browser: microsoft edge
 - Version: widoco-1.4.14-jar-with-dependencies

**Additional context**
java version: java 11.0.1
protege version: Protege-5.5.0-win

**Comment by dgarijo** [comment]
Hi,
Please provide the error when executing through the terminal and  the
ontology file that generates the error. Otherwise it's impossible for me to
know what could have gone wrong.

**Comment by LiniXiang** [comment]
Sorry, I solved this problem myself. Just put widoco and protege in the same folder and they will work normally. 
Thank you for taking the time to answer my question. In addition, thanks to widoco for enabling me to promote the ontology I created. This is so meaningful!

**Comment by dgarijo** [comment]
Ok, then i will close the issue. If you like Widoco, please give it a star, it gives it visibility :)
Thanks!
