### ISSUE TITLE
oops evaluation not generated in version 1.4.15

### ISSUE THREAD

**Issue by mvanbrab** [dgarijo/Widoco#464]
**Describe the bug**
When running **widoco-1.4.15-jar-with-dependencies.jar**, there is no oops evaluation in the output.

**To Reproduce**

1. Execute this command
```
java -jar widoco-1.4.15-jar-with-dependencies.jar -ontFile test.ttl -outFolder output15 -getOntologyMetadata -oops -rewriteAll -htaccess -webVowl -excludeIntroduction > log15.txt 2>&1
```
2. Go to the output directory

3. See that the OOPSevaluation subdirectory is missing

**Expected behavior**
The output directory should contain an OOPSevaluation directory, as is the case when executing this command using 1.4.14:
```
java -jar widoco-1.4.14-jar-with-dependencies.jar -ontFile test.ttl -outFolder output14 -getOntologyMetadata -oops -rewriteAll -htaccess -webVowl -excludeIntroduction > log14.txt 2>&1
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Browser: n.a.
- Version: n.a.

**Additional context**
Input and output of the command lines (test.ttl, log15.txt, log14.txt):
[bug.zip](https://github.com/dgarijo/Widoco/files/6802892/bug.zip)

Java version:
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment Zulu14.29+23-CA (build 14.0.2+12)
OpenJDK 64-Bit Server VM Zulu14.29+23-CA (build 14.0.2+12, mixed mode, sharing)

Hint:
The 1.4.14 output contains a file **ontology.xml**; the 1.4.15 does not, but contains a file **ontology.rdf**.

> When I copy ontology.rdf to ontology.xml and run again, it works!

**Comment by dgarijo** [comment]
Hmm, weird I have a test for checking that. Maybe I forgot to rename a file. Thanks!

**Comment by mvanbrab** [comment]
The extension change from .xml to .rdf seems to be applied consistently in the output, but [this line in the code](https://github.com/dgarijo/Widoco/blob/28269d41f2cef0a327660a9e6a99a0710ee1df24/src/main/java/widoco/CreateOOPSEvalInThread.java#L68) needs an update for oops evaluation to work again, I guess.

**Comment by dgarijo** [comment]
I will update the JAR as well in 1.4.15 so this issue remains fixed. Thanks @mvanbrab!
