### ISSUE TITLE
Entities with slash URI treated as external by WebVOWL 

### ISSUE THREAD

**Issue by tjroamer** [dgarijo/Widoco#469]
**Description**
When running Widoco with -webVowl option on an ontology with slash URI, the locally defined entities are shown as `external`, which makes difficult to recognize which classes are imported, which local, because all of them have the same blue color.

**To Reproduce**

With this file:
```
@prefix : <http://example.org/my#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://example.org/my> .

<http://example.org/my> rdf:type owl:Ontology ;
                         owl:imports <http://www.w3.org/2004/02/skos/core> .

#################################################################
#    Classes
#################################################################


###  http://example.org/my#MyClass2
:MyClass2 rdf:type owl:Class ;
          rdfs:subClassOf <http://www.w3.org/2004/02/skos/core#Concept> .


###  http://example.org/my/MyClass1
<http://example.org/my/MyClass1> rdf:type owl:Class ;
                                 rdfs:subClassOf <http://www.w3.org/2004/02/skos/core#Concept> .


###  Generated by the OWL API (version 5.1.14) https://github.com/owlcs/owlapi/
```
`MyClass2` has a light-blue color, which is correct, but `MyClass1` is marked as `external` class, which is wrong.

**Expected behavior**
`MyClass2` has a hash URI `http://example.org/my#MyClass2`, while `MyClass1` has a slash URI `http://example.org/my/MyClass1`. Both are defined locally in the current ontology file, which imports the `skos` ontology. I expected both classes are showing a light-blue color without `external` annotation.

**Screenshots**
![image](https://user-images.githubusercontent.com/386639/127971236-0f2d8b51-a3eb-4ac8-9b9c-f804eb3d54dd.png)

**Comment by dgarijo** [comment]
I feel like this may be an issue related to WebVowl, rather than Widoco, as we don't do any treatment to the ontology, we just convert to their format.
That said, in this document you seem to have 2 namespaces, `@prefix : <http://example.org/my#> .` and `@base <http://example.org/my> .`; and none of them are declared with a slash. Have you tried declaring a prefix with the slice explicitly?

**Comment by tjroamer** [comment]
Yes, I also tried to declare it explicitly with this example:

```
@prefix : <http://example.org/my#> .
@prefix my: <http://example.org/my/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@base <http://example.org/my> .

<http://example.org/my> rdf:type owl:Ontology ;
                         owl:imports <http://www.w3.org/2004/02/skos/core> .

#################################################################
#    Classes
#################################################################

###  http://example.org/my/MyClass1
my:MyClass1 rdf:type owl:Class ;
            rdfs:subClassOf skos:Concept .


###  Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi
```
The namespace `my` is declared with slash base URI. The resulting graph:

![image](https://user-images.githubusercontent.com/386639/128011095-3b6a60ab-d813-47af-afe9-b20958c38e5f.png)

If it is the problem of the WebVOWL, is there anything that we could do? How to report this issue about WebVOWL? 

We are using slash URIs in our ontology, which contains just tens of classes, but the ontology imports many other ontologies. It is hard to find out which classes are defined locally now.

Thanks.

**Comment by dgarijo** [comment]
Also, in your example it could be still be getting :my as external because
the declared ontology does not end in slash

**Comment by tjroamer** [comment]
Great catch, thanks. I added a slash to the ontology URI, and now the classes with slash URI are showing light-blue color, meaning local. Is it standard that the ontology URI should end with a slash? In case of hash, it seems that we don't need to do that.

**Comment by dgarijo** [comment]
In my experience the ontology URI should contain the trailing symbol
(either hash or slash) or there could be problems with how it is
interpreted. Great to hear it's solved. Please close the issue in case it
is addressed.

**Comment by tjroamer** [comment]
Did you perhaps mean prefix definitions? I haven't found any reference to indicate ontology URI should end with trailing slash or hash. Could you point out one if you have? All of our ontologies don't follow this convention. I added that slash in the above example just for test purpose. I do think it is a problem of WebVowl. I will report it in WebVowl. Thanks.
