### ISSUE TITLE
Are there alternative CSS examples (i.e., examples of using `-useCustomStyle`)...?

### ISSUE THREAD

**Issue by pmcb55** [dgarijo/Widoco#470]
**Is your feature request related to a problem? Please describe.**
Although the README.md says:
```
`-useCustomStyle`: Export the documentation using alternate css files
```
There is no guidance on how to go about doing this. For instance, it says files (plural), so how many CSS files am I supposed to provide to this command-line switch, and is their order important, etc.?

For instance, where are the existing CSS (so that I can see what I need to replace). They seems to be in `src/main/resources/lode` ('cos that's the only folder I can find with **_any_** CSS files). That folder has 7 CSS files, so which file (or files) is `-useCustomStyle` used to replace?

Really, I'm just interested to see alternative look-and-feels, to see what alternative CSS setups other people have used (and might have shared).

**Describe the solution you'd like**
Just examples of other CSS files people have created (and an example of the command-line using `-useCustomStyle` to generate the differently presented HTML).

**Describe alternatives you've considered**
My alternative is to try and reverse-engineer what the current code is doing - which feels like a lot of work!

**Additional context**
I'm just interested in automatically producing relatively simple HTML for a glossary that I've defined as an RDF ontology, and where that HTML looks-and-feels like existing HTML documentation that we have already.

**Comment by dgarijo** [comment]
Hi @pmcb55,
if you use `useCustomStyle`, you don't have to provide alternative CSS files. Widoco will generate the documentation using the styles in https://datos.bne.es/def/ontology.html. 
I hope this chunk of code helps clarify which css are used (by default, useCustomStyle is true):
```
if (c.isUseW3CStyle()) {
			WidocoUtils.copyLocalResource("/lode/lodeprimer.css",
					new File(resources.getAbsolutePath() + File.separator + "primer.css"));
			WidocoUtils.copyLocalResource("/lode/rec.css",
					new File(resources.getAbsolutePath() + File.separator + "rec.css"));
			WidocoUtils.copyLocalResource("/lode/extra.css",
					new File(resources.getAbsolutePath() + File.separator + "extra.css"));
			WidocoUtils.copyLocalResource("/lode/owl.css",
					new File(resources.getAbsolutePath() + File.separator + "owl.css"));
		} else {
			WidocoUtils.copyLocalResource("/lode/bootstrap-yeti.css",
					new File(resources.getAbsolutePath() + File.separator + "yeti.css"));
			WidocoUtils.copyLocalResource("/lode/site.css",
					new File(resources.getAbsolutePath() + File.separator + "site.css"));
		}
```

**Comment by pmcb55** [comment]
Ah - thanks @dgarijo. I don't know why I thought Widoco supported multiple look-and-feels out of the box (I think I may have been confusing it with [Dokeli](https://dokie.li/)), but that certainly explains the current situation (and in fact Widoco does currently support two look-and-feels, so that's helpful and useful) - so I'll close this issue. Thanks.
