### ISSUE TITLE
Upper/Lowercase mix ?

### ISSUE THREAD

**Issue by lolostar** [dgarijo/Widoco#482]
Hi all,

I have a class **Eval** and an ObjectProperty **eval** in the same ontology.

**Eval** doesn't appear in the list of Classes although it appears in the **eval** ObjectProperty description but labeled as 'eval' (lowercase).  Click on this **eval**  leads to nothing
<img width="449" alt="Capture d’écran 2021-11-12 à 14 46 13" src="https://user-images.githubusercontent.com/13002994/141477236-6302be83-e0fe-4c40-ac17-e8a9a7ebbef0.png">

Is there a problem here because Widoco mixes lower/upper case ?

Regards,

Laurent

**Comment by dgarijo** [comment]
Hi Laurent,
as far as I know, Widoco will use the term ids for creating their anchors. If you use the same for a property and a class, there may be issues. So it's not a case of lowercase/uppercase, it's a matter of javascript not knowing what to resolve. There is no good solution because if you change the id, then the term URI will not resolve correctly to that section

**Comment by lolostar** [comment]
Hi Daniel,

http://data.edf.fr/optimisation/ontology/formula#Eval is the Class URI
and
http://data.edf.fr/optimisation/ontology/formula#eval is the ObjectProperty URI
They have different ids no ?

**Comment by dgarijo** [comment]
They do, but I don't know if in javascript this means having two distinct anchors. They should!
Maybe the library used to go to the right section does not take this into account. I will have to have a look

**Comment by lolostar** [comment]
Hi Daniel,

Looking through previous issues I found that the Eval class didn't have any axiom associated with it.  I just added one (Disjointness) and Eval new appears in the Class list :)

Regards

Laurent

**Comment by dgarijo** [comment]
If you add a label it should suffice as an annotation for the class.
One question, does the issue with the id get resolved? (I think they are two separate things)
If the issue with the id is resolved, please feel free to close the issue
