### ISSUE TITLE
schema:creator does not produce list of authors

### ISSUE THREAD

**Issue by ldesousa** [dgarijo/Widoco#485]
**Describe the bug**
I am trying to use Schema.org to add meta-data to my ontologies as it allows for complex individuals (compared with the literals in Doublin Core). Here is an example:

```
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix schema: <http://schema.org/> .

<http://orcid.org/0000-0002-5851-2071> a schema:Person ; 
                          schema:name "Luís M. de Sousa" ;
                          schema:affiliation [ a schema:Organization ;
                                               schema:name "ISRIC - World Soil Information"
                                             ] .

<http://example.com/test>
        a                owl:Ontology ;
        owl:versionIRI   <http://example.com/test/1.0> ;
        owl:versionInfo  "1.0" ;
        schema:creator <http://orcid.org/0000-0002-5851-2071> ; 
        dct:title "My test Ontology"@en .
```

With the above Widoco does not produce an authors list (see screen capture below). I also tried with a blank node:

```
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix schema: <http://schema.org/> .

<http://example.com/test>
        a                owl:Ontology ;
        owl:versionIRI   <http://example.com/test/1.0> ;
        owl:versionInfo  "1.0" ;
        schema:creator [ schema:name "Luís M. de Sousa" ;
                         schema:affiliation [ a schema:Organization ;
                                               schema:name "ISRIC - World Soil Information"
                                             ] .
                       ] ; 
        dct:title "My test Ontology"@en .
```

But the result is the same.

**To Reproduce**
Steps to reproduce the behaviour:
1. Save one of the ontologies above into a `.ttl` file.
2. Run Widoco on it and open the browser.

**Expected behaviour**
An authors list is expected, since `schema:creator` is listed in the [Best Practices](https://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html#creators) document.

**Screenshots**
![test01](https://user-images.githubusercontent.com/1137878/144445069-6b7b51b8-e976-4c0b-a5b7-97a71fe4ce7f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Brave
 - Version 1.4.15

**Comment by dgarijo** [comment]
Hello,
please try with https: `https://schema.org/creator`.
I think I changed it to `https` when they upgraded the schema :)

**Comment by dgarijo** [comment]
Blank nodes are not recognized, this is an open issue.

**Comment by ldesousa** [comment]
Thank you for the swift reply. Modifying the URI to `https` indeed produced an authors list. However, instead of using the `schema:name` property, the list shows the individual URI directly. You can see the result below:

![test01](https://user-images.githubusercontent.com/1137878/144458889-54929235-2e77-40fd-b0ba-188518f14aef.png)

I was instead expecting to see the Person name, perhaps with a link to the URI, like the example in the [gallery](https://dgarijo.github.io/Widoco/doc/gallery/images/metadata.png).

**Comment by dgarijo** [comment]
That's issue https://github.com/dgarijo/Widoco/issues/285.
Will deal with it in the next release.

**Comment by dgarijo** [comment]
I will leave it open until it's addressed
