### ISSUE TITLE
bibo:status not considered as specified

### ISSUE THREAD

**Issue by weissjoh** [dgarijo/Widoco#486]
**Describe the bug**
In the actual version of WiDoCo (1.4.15) the bibo:status is used as a xsd:String. However, the bibo:status is not a DataTypeProperty but an ObjectProperty. The target type should be a bibo:DocumentStatus. One example is "http://purl.org/ontology/bibo/status/published". If such an IRI is used, then WiDoCo renders as status "Ontology Specification Draft" - which is wrong.
See: http://gbol.life/ontology/bibo/status/
And: http://gbol.life/ontology/bibo/DocumentStatus/

**To Reproduce**
Within your ontology, define a bibo:status which uses a bibo:DocumentStatus, e.g.
```
bibo:status <http://purl.org/ontology/bibo/status/published> ;
```
Then render your ontology with WiDoCo

**Expected behavior**
Expected behavior is, that the definition of the defined bibo:DocumentStatus shall be displayed. In this case instead of "Ontology Specification Draft" it shall be "Published document" - as defined by the rdfs:comment of http://purl.org/ontology/bibo/status/published.

**Additional context**
Rather the question if this issue is related to WiDoCo or the underlying LODE. Haven't found any hints by analyzing the code.

**Comment by dgarijo** [comment]
Hi @weissjoh,
good catch. This is a WIDOCO problem indeed (LODE does not recognize this last time I checked).
Will fix this in the next release.
I think I will still keep the support for the wrong usage, even if it's not correct.
