### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by engapa** [dgarijo/Widoco#499]
**Describe the bug**
Docker build fails due to is using a wrong output directory named "jar" instead "JAR"

**To Reproduce**
`docker build -t widoco .`

```
mv: cannot stat './jar/widoco*.jar': No such file or directory
The command '/bin/sh -c mvn package &&     mv ./jar/widoco*.jar ./jar/widoco.jar' returned a non-zero code: 1
```

**Expected behavior**
Docker image is built successfully

**Solution**
Change directory name of "JAR" to "jar"  in pom.xml. Or inverse change in the Dockerfile file

**Comment by dgarijo** [comment]
Fixed by https://github.com/dgarijo/Widoco/commit/b48fb4178480ca09b9497ef6aaf3cc5373beeeb9
