### ISSUE TITLE
Unsupported major.minor version 52.0" exception on launching v1.4.16

### ISSUE THREAD

**Issue by fleert** [dgarijo/Widoco#503]
**Describe the bug**
v1.4.16 does not start, returns JNI error:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: widoco/gui/GuiController has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**To Reproduce**
1. Download v1.4.16 jar
2. Open cmd
3. Check java version: `java -version`: `java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)`
5. Try to start Widico v1.4.16 using `java -jar widoco-1.4.16-jar-with-dependencies.jar`
6. Error: `Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: widoco/gui/GuiController has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Expected behavior**
Widico will start

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Not latest version of Widico v1.4.15 does launch properly

**Comment by fleert** [comment]
> @fleert, thanks for testing out Widoco. I updated the Java version to 11, in order to fix a few things. You need to update your Java version to a more recent one, and Widoco will continue working. Otherwise, you can continue using v 1.4.15. Or try building the jar yourself by doing `mvn install` in the repo.
> 
> I will leave this issue open because I need to update the readme with this information.

hi Daniel. thanks. But I don't understand. Obviously, the first thing I did was update my Java. According to https://www.java.com/en/download/ the version I have installed is the newest java version "1.8.0_321". So how I can update?

**Comment by dgarijo** [comment]
@fleert,
see if the new release JARs fix this issue. Now they are compiled for different Java versions. Try the 11 one and see if it works now: https://github.com/dgarijo/Widoco/releases/tag/v1.4.17

**Comment by dgarijo** [comment]
Closing because it looks resolved. Please reopen if appropriate.
