### ISSUE TITLE
Cannot build docker image

### ISSUE THREAD

**Issue by renefritze** [dgarijo/Widoco#505]
**Describe the bug**
The docker image build fails with a test error.

> #12 78.19 Tests in error: 
#12 78.19   testPrintEvaluation2(oops.OOPSevaluationTest): Cannot invoke "org.semanticweb.owlapi.model.OWLOntology.getOWLOntologyManager()" because "this.model" is null
#12 78.19   testPrintEvaluation(oops.OOPSevaluationTest): Cannot invoke "org.semanticweb.owlapi.model.OWLOntology.getOWLOntologyManager()" because "this.model" is null

**To Reproduce**

```
git clone https://github.com/dgarijo/Widoco /tmp/Widoco
cd /tmp/Widoco
docker build .
```
 [Complete docker output](https://github.com/dgarijo/Widoco/files/8474559/docker.log.txt)

**Comment by dgarijo** [comment]
@renefritze btw, it's holidays this week in Spain, so the ws will likely work again in one week.

**Comment by renefritze** [comment]
Thanks for the heads up. Using the release JAR works for me. I saw that you don't have CI (Github Actions) to regularly build the image. I'd be happy to contribute that.

**Comment by dgarijo** [comment]
I would appreciate it! Thanks!

**Comment by dgarijo** [comment]
@renefritze please give it a try, it should be working now.
