### ISSUE TITLE
Dead link in docs/gallery

### ISSUE THREAD

**Issue by renefritze** [dgarijo/Widoco#508]
https://github.com/dgarijo/Widoco/blob/c4da2f5e3a008bc4ec3b15db9357881d7bf9cb14/doc/gallery/index.html#L76
 The link to http://linked.earth/ontology/core/1.2.0/ results in 404, presumably since there's no default index.html for github to serve there.

Also the [index-en.html](http://linked.earth/ontology/core/1.2.0/index-en.html) points to itself using the wrong URL too, but I didn't see where the source is hosted to report that there too

**Comment by dgarijo** [comment]
Ouch, nice catch, will fix this right away.

**Comment by renefritze** [comment]
I found another:
 - https://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html "bibo:status" is a TODO

**Comment by dgarijo** [comment]
will be fixed in next PR to main
