### ISSUE TITLE
Ability to retain indent and newlines in literal values

### ISSUE THREAD

**Issue by tfrancart** [dgarijo/Widoco#519]
**Is your feature request related to a problem? Please describe.**
My ontologies contains SPARQL query expressed in literals. Of course in these SPARQL queries the indent and newlines are important. But they are lost in the HTML rendering. Example at http://data.sparna.fr/ontologies/sparnatural-config-datasources/index-en.html#query_tree_children_with_count

**Describe the solution you'd like**
Maybe a flag to add a "pre" tag around literals ? or add a special handling by reacting on some datatype ?

**Describe alternatives you've considered**
No alternatives considered

**Additional context**

Screenshot of queries linked above :

![image](https://user-images.githubusercontent.com/2728945/164279648-c4c7bd3a-85cd-4f27-aae1-b69653369d42.png)

and in the source code:

![image](https://user-images.githubusercontent.com/2728945/164279961-cbcc123f-3daa-47bd-b8ca-1608f7455310.png)

**Comment by dgarijo** [comment]
@tfrancart,
I set up markdown support in literals from descriptions, etc. In theory if you write your query with within ```, it should render the query as you intend.

**Comment by dgarijo** [comment]
See https://github.com/dgarijo/Widoco/blob/master/doc/gallery/images/md.png

**Comment by tfrancart** [comment]
I can't use Markdown unfortunately. I need the clean and valid SPARQL query in the ontology (because it is read by some application). Probably this is a very special case and the feature you indicate already covers the needs of most people.

**Comment by dgarijo** [comment]
Ok, then I'll close the issue for now.
