### ISSUE TITLE
dcterms:title not in generated documentation

### ISSUE THREAD

**Issue by janvlug** [dgarijo/Widoco#530]
**Describe the bug**
WIDOCO does not generate a title in the documentaton for this ontology: [metadatatestont.zip](https://github.com/dgarijo/Widoco/files/8701385/metadatatestont.zip)

But when the line `rdfs:subPropertyOf dcterms:title ;` is out-commented, a title will be generated in the documentation

**To Reproduce**
1. run `java -jar <path_to_jar>/java-11-widoco-1.4.17-jar-with-dependencies.jar -ontFile medatatestont.ttl -outFolder ./generated -getOntologyMetadata -uniteSections`
2. Open the generated documentation
3. Note that there is no title for the ontology in the generated documentation.

**Expected behavior**
There is a title for the ontology in the generated documentation.

**Comment by dgarijo** [comment]
Hmm, it seems like when you add the annotation property as a superproperty, it stops being recognized as an annotation property... I will have to have a look to see if we can retrieve all assertions from the ontology itself

**Comment by GenEars** [comment]
Hello. I get the same behavior (i.e. missing ontology name and `[Ontology Name]` place holder text in titles) when defining a `rdfs:subPropertyOf dcterms:title ;` in a `owl:DatatypeProperty`:

```
noria:logText
	a owl:DatatypeProperty ;
	rdfs:label "logText" ;
	rdfs:comment "Textual information describing the logged event." ;
	rdfs:domain noria:EventRecord ;
	rdfs:range xsd:string ;
#	rdfs:subPropertyOf dcterms:title ;  # TODO: using dcterms:title entails Widoco rendering issue of the ontology name
```

Note that I found this behavior with both *java-17-widoco-1.4.17-jar-with-dependencies* and *widoco-1.4.19-jar-with-dependencies_JDK-17* releases. Further, using *widoco-1.4.19-jar-with-dependencies_JDK-17* breaks markdown rendering from `rdfs:comment`.

**Comment by dgarijo** [comment]
It seems like it's the same issue: when a property is extended, it does not recognize it as an annotation property. 

Markdown problems were addressed last time I checked. Can you please open a new issue with the details @GenEars?
I fixed some issues not so long ago addressing markdown problems.

**Comment by dgarijo** [comment]
I pushed a commit fixing the issue, will do a new release in the next couple of days
