### ISSUE TITLE
Unable to generate links in the annotation property rdfs:comment

### ISSUE THREAD

**Issue by ednaru** [dgarijo/Widoco#541]
**Describe the bug**
Have tried to generate links in the rdfs:comment of a class or property as markdown, but are deployed in the documentation as text

**Example**
 rdfs:comment in Protégé
![Screenshot 2022-06-16 at 17 05 59](https://user-images.githubusercontent.com/28527231/174101335-7cbe7803-3154-4c8b-b11a-5c8023549bdb.png)

It is deployed in the documentation as text:

![Screenshot 2022-06-16 at 17 06 33](https://user-images.githubusercontent.com/28527231/174101391-eaf88617-d2ee-4b99-b495-65d3d20833ce.png)

**Comment by dgarijo** [comment]
The javascript library (now update) needs to be called differently now. It works now, but I need to produce a new release
