### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by janvlug** [dgarijo/Widoco#542]
**Describe the bug**
When I generate Dutch (NL) documentation, Geïmporteerde ontologieën (Imported ontologies) is incorrectly encoded. See screenshot:

![image](https://user-images.githubusercontent.com/5903208/176155765-17fb8db6-4c33-4cc5-bf7c-9a808b73138f.png)

**To Reproduce**
1. Generate the Dutch (NL) documentation for an ontology.

**Expected behavior**
Correct encoding of letters like ï and ë.

**Desktop**
 - OS: Fedora 36
 - Firefox, Chromium, Chrome
 - WIDOCO 1.4.17

**Comment by dgarijo** [comment]
Nice catch! I will fix this soon
