### ISSUE TITLE
Properties for generating introduction and description sections

### ISSUE THREAD

**Issue by gkirtzou** [dgarijo/Widoco#544]
Dear Widoco team,
i am trying to generate documentation using the Widoco throught Ontoology (http://ontoology.linkeddata.es/) and I cannot undestand which properties would generate the text for the Introduction and Description section of the html generate pages.

I have tried rdfs:comment, dc:description the only take that changes is in the abstract section. Could you please point me to the correct direction? 

PS. In the documentation of best practices (https://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html#intro), for the abstract you mention to use "Properties you may use: [dc:abstract](http://purl.org/dc/elements/1.1/description) [dcterms:abstract](http://purl.org/dc/terms/abstract)" by there is no dc:abstract property defined in DC vobulary, and if you notice the url points to dc:description.

**Comment by gkirtzou** [comment]
You can check the pull request generated by ontoology here:
https://github.com/gkirtzou/LexMeta/pull/15/commits/607148481b556db2cfe942e81e4cec9acf99565d#diff-1802b9d76c75894923aca057775a0070ae21aa7c0ff9379742aa875dd7bd8cef

**Comment by dgarijo** [comment]
The property should be https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/abstract, it's a typo in the ontology. In theory, adding any of those should work. Your abstract will be based on those.

In the pull request you sent by OnToology the abstract is based on your description (https://github.com/gkirtzou/LexMeta/commit/607148481b556db2cfe942e81e4cec9acf99565d#diff-1802b9d76c75894923aca057775a0070ae21aa7c0ff9379742aa875dd7bd8cef)
So I guess it has worked?

**Comment by gkirtzou** [comment]
In the commit I sent above, I have both a rdfs:comment and a dc:description and given the information in the Best practices page (https://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html#intro), I would expect to have the dc:description in the Abstract section and the rdfs:comment value in the Description section. But what I get is rdfs:comment value in Abstract, and placeholder text for Introduction and Description. 

So, my question is which are the properties that would generate text in the description.html and introduction.html pages respectively.

**Comment by dgarijo** [comment]
At the moment (if I remember correctly), the abstract and description are both used in the summary section of the HTML. Intro and description is something left out to complete by hand

**Comment by gkirtzou** [comment]
Ahhh if that's the case, then I would need to manually change this information in the generated html pages. Maybe ypu need to clarify that in the Best practices document, cause from our understanding, we did expect to Section 3.2.2 - Description (recommended) and Section 3.2.3 - Abstract (optional) would generate different areas in the html documentation, not the same. Given that LODE (https://essepuntato.it/lode/) used to do that as well.

**Comment by dgarijo** [comment]
This is a good point. If there is a description I may copy it in the description section always. And then if you have a different abstract, add the abstract there. I will leave the issue open until this is addressed. Sorry for the confusion

**Comment by jfaldanam** [comment]
Is there any update on this? It will be useful to avoid any kind of manual postprocessing of the HTML to generate the ontology automatically.

**Comment by dgarijo** [comment]
Hi @jfaldanam, I have been working on documenting which properties are used where, but I have not found the time to address this one yet, sorry. I would like to spend some additional time soon (if I can ) to address it

**Comment by dgarijo** [comment]
Now that I had the time to work on #436, next release will address this issue
