### ISSUE TITLE
Question: Best way to load custom introduction/description via CLI

### ISSUE THREAD

**Issue by Maximvdw** [dgarijo/Widoco#549]
In the GUI it is possible to load a custom introduction/description html file. Is a similar thing possible via the command line interface?
I do not immediately see cli options available, but I was maybe thinking if the configuration file could be used to set the `introductionPath` (my first attempts to try this were unsuccessful)?

If there is currently no other way than the GUI to load the content, I think I will just wait for: https://github.com/dgarijo/Widoco/issues/544 ;)

PS: I use the `uniteSections` option, so overriding the `introduction-en.html` file is not an option

Thanks,
Maxim

**Comment by dgarijo** [comment]
@Maximvdw, 
I thought this was possible with `-confFile PATH`, but I don't find an example, so I think it's not currently supported. I am overdue for a Widoco release, #544 should be addressed. I aim to do it in August

**Comment by dgarijo** [comment]
This has now been addressed. You can use the `widoco:introduction` and `dc:description` property in the ontology metadata, or you can choose the `introduction` and `description` properties in the configuration file. See https://github.com/dgarijo/Widoco/blob/master/doc/metadataGuide/guide.md for more information. Will do a release in a couple of days once I address a few more issues
