### ISSUE TITLE
Wrong label if multiple labels are provided

### ISSUE THREAD

**Issue by marioscrock** [dgarijo/Widoco#556]
**Describe the bug**
A label with duplicated text is generated if both `rdfs:label` and `skos:prefLabel` are used. I assume the same error would happen if `obo:IAO_0000118` is provided.

**Expected behavior**
I solved the issue by changing the `extraction.xsl` file and removing `skos:prefLabel`, however a better solution should be found to keep the `or` condition and do not add the duplicated text (select only one label if multiple labels are provided).

**Screenshots**
![duplicated label](https://user-images.githubusercontent.com/5709852/188824919-9a9e6c53-7d6b-4d3a-a305-f41aa7f3cc78.PNG)

**Comment by dgarijo** [comment]
I think this is the first time I see someone having an issue due to too many annotations :)
You are correct, an OR is needed (or similar).
