### ISSUE TITLE
Bad zip entry

### ISSUE THREAD

**Issue by janvlug** [dgarijo/Widoco#557]
**Describe the bug**
When I'm running WIDOCO in a GitLab CI/CD job, I get (sometimes?) this error:

```
[main] INFO widoco.gui.GuiController - Generating documentation for ./myont.ttl in lang nl
[main] INFO widoco.gui.GuiController - Load properties from the ontology in lang nl
[main] INFO widoco.CreateResources - Generate documentation in ./generated/myont-1.0.5-SNAPSHOT
[main] INFO widoco.CreateResources - - ontology IRI: https://identifier.my.nl/blah/def/ont
[main] INFO widoco.LODEParser - Parsing Complete!
[main] ERROR widoco.gui.GuiController - Error while generating the documentation: Bad zip entry
java.lang.RuntimeException: Bad zip entry
	at widoco.WidocoUtils.unZipIt(WidocoUtils.java:262)
	at widoco.CreateResources.createFolderStructure(CreateResources.java:471)
	at widoco.CreateResources.generateDocumentation(CreateResources.java:86)
	at widoco.gui.GuiController.<init>(GuiController.java:275)
	at widoco.gui.GuiController.main(GuiController.java:501)
```
**To Reproduce**
1. Run WIDOCO in a GitLab CI/CD job
2. With this command: `java -jar /usr/local/widoco/widoco.jar -ontFile ./${ONTOLOGY_NAME}.ttl -doNotDisplaySerializations -outFolder ./generated/${ONTOLOGY_NAME}-${ONTOLOGY_VERSION} -getOntologyMetadata -lang nl -uniteSections -webVowl -rewriteAll`

**Expected behavior**
The documentation will be available

**Additional context**
Happens (sometimes?) in a GitLab CI/CD job.
I vaguely remember I had seen this error before, and it went away for unknown reasons, but now I get this error every time.

**Comment by janvlug** [comment]
After some more testing, I now think (but I'm not 100% sure) that the issue only happens when creating the webvowl.
Maybe the java process has no permission to create a directory.

The error happens in this code:
```
if (c.isCreateWebVowlVisualization()) {
	File webvowl = new File(s + File.separator + "webvowl");
	webvowl.mkdir();
	WidocoUtils.unZipIt(Constants.WEBVOWL_RESOURCES, webvowl.getAbsolutePath());
}
```
I will try to investigate further details about directory creation permissions in images run in GitLab CI/CD pipelines.
I confirm that I do not have this error when running the WIDOCO Docker image on a Linux host directly. It only happens in the GitLab CI/CI pipeline.

**Comment by dgarijo** [comment]
All right please keep me in the loop!

**Comment by dgarijo** [comment]
There has been no update on this issue, so closing. Please reopen if appropriate.
