### ISSUE TITLE
isDefinedBy not being properly recognized for data property

### ISSUE THREAD

**Issue by inaja** [dgarijo/Widoco#588]
In the PECO ontology (https://w3id.org/peco)
The data property http://qudt.org/schema/qudt/value has rdfs:isDefinedBy "https://qudt.org/schema/qudt/". But the generated widco file shows: is defined by https://w3id.org/peco# 

![image](https://github.com/dgarijo/Widoco/assets/202545/7738c113-cb24-4a38-8184-f1f3569e1821)

**Comment by dgarijo** [comment]
This only happens when `rdfs:isDefinedBy` points to a literal. According to https://www.w3.org/TR/rdf12-schema/#ch_isdefinedby, the range of `isDefinedBy` should be a `rdfs:Resource`. In this case, the ontology annotation is wrong

**Comment by dgarijo** [comment]
I added a fix so if the value is not a resource, then do not complete with the ontology name by default
