### ISSUE TITLE
Licensius not available

### ISSUE THREAD

**Issue by stefanogermano** [dgarijo/Widoco#607]
**Describe the bug**

When you use the `-licensius` option, you get the following error:

> [main] ERROR licensius.GetLicense - -->Could not load license for vocab: Unexpected end of file from server

**To Reproduce**

1. Run WIDOCO with the `-licensius` option
2. See the error

**Expected behavior**

No error (or clearer error message).

**Comment by dgarijo** [comment]
This one is fixed, but I have not committed yet. The service endpoint changed.
