### ISSUE TITLE
Some vocabulary annotations only work from the `config.properties` file, not from the TTL source

### ISSUE THREAD

**Issue by Zack-83** [dgarijo/Widoco#614]
**Is your feature request related to a problem? Please describe.**
I really appreciate the new update of the software and documentation.

It seems that the `config.properties` cannot be completely dropped yet. Some vocabulary annotations do not have an equivalent annotation property (extended-/importedOntologyNames/-URIs; latestVersionURI), while some others are overwritten/superseded by the ones from the `config` file (ontologyName; dateOfRelease).

As an example, the table of content snapshot was generated asasigning rdfs:label in the TTL and commenting ontologyName in the config.

![image](https://github.com/dgarijo/Widoco/assets/37865804/ac77e946-aa94-4a0f-bf27-6f50d2505573)

An overview of the missing/problematic fields is given in the table below.

|Metadata category|Ontology annotation property*|config.properties field(s)**|Remarks       |
|-----------------|-----------------------------|----------------------------|--------------|
|Modification date|dcterms:modified, schema:dateModified|modified, dateOfRelease|dateOfRelease supersedes modified|
|Ontology name      |???|ontologyName              |rdfs:label does not work: requires ontologyName|
|Extended ontologies|???|extendedOntologyNames, extendedOntologyURIs|only in `config.properties`, not in TTL|
|Imported ontologies|owl:imports?|importedOntologyNames, importedOntologyURIs|only in `config.properties`, not in TTL|
|Latest version|???|latestVersionURI                       |only in `config.properties`, not in TTL|
|Serialization |???|RDFXML-/Turtle-/N3-/JSONLDSerialization|only in `config.properties`, not in TTL|

**Describe the solution you'd like**
Either we find and implement suitable annotation properties, or we specify in the two guides that some annotations should be input necessarily through the config file.

I can help with the documentation.

**Comment by dgarijo** [comment]
Ontology Name should be the title, if I remember correctly. And the latest version is driven (or should be) by vann:preferredNamespaceUri. I will have to have a look at the others. There is an overlap with recent issues, but I do agree these problems are pressing

**Comment by Zack-83** [comment]
> Ontology Name should be the title, if I remember correctly. And the latest version is driven (or should be) by vann:preferredNamespaceUri. I will have to have a look at the others. There is an overlap with recent issues, but I do agree these problems are pressing

vann:preferredNamespaceUri is **this** version (not necessarily the last one).
ontologyName is just one word (ex.: "Metadata4Ing") while the ontologyTitle is a half-sentence (ex.: "Metadata4Ing: An ontology for describing the generation of research data within a scientific activity.")

**Comment by dgarijo** [comment]
The namespace URI is the ontology URI, so it should be the one for last version (it should not change across different versions). owl:versionIRI should be the one for **this version**. Don't you agree?
I agree about the title. Maybe we can use the rdfs:label of the ontology.

**Comment by dgarijo** [comment]
Latest commits fix this issue. I will do a release implementing in the next couple of days
