### ISSUE TITLE
widoco:introduction not working

### ISSUE THREAD

**Issue by psiotwo** [dgarijo/Widoco#658]
**Describe the bug**
Having specified :o a owl:Ontology; widoco:introduction "Introduction"@en does not generate the introduction section:

```java -jar widoco.jar -ontFile test_semantic_asset.ont.ttl -outFolder outx -getOntologyMetadata -noPlaceHolderText -includeAnnotationProperties```

Using Widoco 1.4.20.

**Comment by vChavezB** [comment]
I did a quick test and think this happens of the option  ` -noPlaceHolderText` is included

**Comment by dgarijo** [comment]
This should affect also the description and abstract then. I will add exceptions if these metadata properties appear in the ontology itself.
