### ISSUE TITLE
Identify type of property assertion for individuals that reference external properties.

### ISSUE THREAD

**Issue by vChavezB** [dgarijo/Widoco#667]
The xslt parser ignores named individual assertions whose URI is not defined in the ontology. 

https://github.com/dgarijo/Widoco/blob/62e3820b569a52b157fa8ce903e3e495d6cbf609/src/main/resources/lode/extraction.xsl#L1178

This means that any assertion which relates to an external ontology will not be displayed. 

## How to reproduce

I made a small ontology sample to reproduce this (turtle file with txt extension due to github blacklisting .ttl files)

[external.ttl](https://github.com/dgarijo/Widoco/files/13810669/external.txt)

These are my assertions for individual car 1. Please ignore the nonsense of the assertions, I just wanted to do a
quick test on different scenarios.

![grafik](https://github.com/dgarijo/Widoco/assets/47216966/22d58a19-82d1-4eaf-ab1b-51737e89f0e7)

and how it looks in WIdoco

![grafik](https://github.com/dgarijo/Widoco/assets/47216966/c40f15ee-3ca4-404f-b636-651f9ed7aedf)

## Suggestion

As we already have the ontology loaded in Widoco with the owlapi, it would be nice to enrich the metadata for external assertions from the ontology itself if provided. Please check my draft PR for  my suggestion #668 

I thought of this since I am working with the QUDT ontology and there you get all assertions for individuals independent if the assertions relate to object properties, named inviduals or data properties that are imported from another ontology.

Example

https://qudt.org/vocab/unit/AT

**Comment by dgarijo** [comment]
Addressed in `develop`, will be there in the next release
