### ISSUE TITLE
Problem with Markdown Support in Widoco Generated HTML

### ISSUE THREAD

**Issue by Rcaschultz** [dgarijo/Widoco#676]
Line 16 in the generated HTML
 
jQuery(".markdown").each(function(el){jQuery(this).after(marked(jQuery(this).text())).remove()});
 
needs to be changed from marked to marked.parse . The function “marked” seems to have been deprecated awhile ago.

This issue breaks the markdown support.

**Comment by dgarijo** [comment]
Thanks a lot for the suggestion!

**Comment by dgarijo** [comment]
@Rcaschultz I double checked and currently the line Widoco produces is the same as the one you suggest.  Maybe you are using an older version of the tool?
This was fixed here: https://github.com/dgarijo/Widoco/issues/541
