### ISSUE TITLE
Missing hasNext() Check Before Using next() in Iterator

### ISSUE THREAD

**Issue by Xiqinger** [dgarijo/Widoco#681]
**Describe the bug**
The current implementation utilizes an Iterator without checking the hasNext() method before calling next(). This can lead to NoSuchElementException if there are no more elements in the Iterator. 
The "printEvaluation" method in the "oops.OOPSevaluation" class utilizes the "elementos.hasNext" check to ensure that "first" has a value. However, it does not guarantee that "second" will have a hasNext() value of true.

**Expected behavior**

**Screenshots**
![image](https://github.com/dgarijo/Widoco/assets/163422483/98ec84a6-b559-45d9-abfe-04dabc643052)
![image](https://github.com/dgarijo/Widoco/assets/163422483/ed37f8e3-7dd5-44cb-b3a4-8cf9d253f510)

**Additional context**
To mitigate this issue, it is recommended to add a hasNext() check before accessing the "second" element, line 350 and line 327 .

**Comment by dgarijo** [comment]
Thanks!!
