### ISSUE TITLE
Host docker image on dockerhub

### ISSUE THREAD

**Issue by MathiasVDA** [dgarijo/Widoco#696]
**Is your feature request related to a problem? Please describe.**
I would like to use the latest version of Widoco in a Docker container without having to build the image myself.

**Describe the solution you'd like**
Automatic build and deploy of the docker image on Dockerhub using github actions.

**Describe alternatives you've considered**
NA

**Additional context**
I can help you with this if you would like. I've already done something similar for sparql-anything: https://github.com/SPARQL-Anything/sparql.anything/issues/404
I will create a merge request with the necessary configuration to be added to the .github folder.

**Comment by dgarijo** [comment]
The image is actually being built and hosted in ghrc with each release. You
don't have to build it from scratch if you don't want :)

**Comment by dgarijo** [comment]
See https://github.com/dgarijo/Widoco/pkgs/container/widoco
```
docker pull ghcr.io/dgarijo/widoco:develop
```

**Comment by MathiasVDA** [comment]
Oh ok... I was so happy that I thought I could help you :)

Ok... never mind then. I will close the pull request. Great job by the way :D

**Comment by dgarijo** [comment]
Thanks for your effort @MathiasVDA. I may still consider your PR to have the docker image in 2 image registries. The reason why we did not go for DockerHub is that in the last years they started requiring upgrading your account even for Open Source projects, plus threatening on removing older images if they were not downloaded enough. They have gone back on those decisions for now, but you never know.

**Comment by MathiasVDA** [comment]
Yes indeed, Docker has made some bad decisions and I understand your reasoning. It's actually my fault to only look on dockerhub for the official image instead of on other repositories. I only saw the mention of building the image yourself in the readme file and I didn't look at the package section of the github page.
