### ISSUE TITLE
Align ontology description to the MOD schema? 

### ISSUE THREAD

**Issue by Zack-83** [dgarijo/Widoco#733]
**Is your feature request related to a problem? Please describe.**
A new schema for ontology description has been produced by an authoritative body. Maybe it 

**Additional context**
https://github.com/FAIR-IMPACT/MOD

Metadata for Ontology Description and Publication Ontology

This project consists in building an OWL ontology and application profile to capture metadata information for ontologies, vocabularies or semantic resources/artefacts in general.

MOD was conceived as an OWL ontology to capture metadata information for ontologies. It is somehow a follow-up to the OMV2 Ontology project. This project is connected to the work done by @jonquet and @antool on a new ontology metadata model implemented within AgroPortal (https://github.com/agroportal): https://github.com/agroportal/documentation/tree/master/metadata
We are currently working on MOD 3 designed as a profile of DCAT 2.

MOD is discussed within the RDA's Vocabulary Services Interest Group and more recently within the H2020 FAIRsFAIR Task 2.2 ("FAIR semantics") and Horizon Europe FAIR-IMPACT's WP4.
See the RDA VSSIG "ontology metadata" TG's working folder: https://drive.google.com/drive/folders/1EqEHwnhjQef9EtjhNifMYVREmdtD26BQ

**Comment by dgarijo** [comment]
@Zack-83, the current metadata descriptions are aligned with MOD recommendations.  `mod:acronym` is directly recognized in https://github.com/dgarijo/Widoco/blob/master/doc/metadataGuide/guide.md

The part that could be better aligned is the distribution declaration, but I have yet to find ontologies using it that way.

**Comment by dgarijo** [comment]
There are other properties that are too registry-specific, like the number of properties and classes, etc. But all ontology properties should be properly recognized.
