### ISSUE TITLE
label of classe in French

### ISSUE THREAD

**Issue by croussey** [dgarijo/Widoco#737]
**Describe the bug**
Class name should be in upper case by convention. Thus in the owl file the label (using skos:prefLabel property) are written in Uppercase. In the english version of the documentation the class names are in upper case, in the french version the class names are in lower case

**To Reproduce**
1. Go to https://rdf.codex.cati.inrae.fr/bag-def
2. Click on fr version
3. Scroll down to 4.1 section 
4. See error the class names

**Expected behavior**
I would like that the class name are in uppercase like in the original file
https://forgemia.inra.fr/bsv/bio-agressor-ontology see bago_onto_latest.owl

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [chrome]
 - Version [131.0.6778.139]

**Additional context**

**Comment by dgarijo** [comment]
@croussey 

Class definitions are also fine:
![image](https://github.com/user-attachments/assets/e05f75c6-713b-47ea-96e7-2877344caff3)

I am not sure what is the error here, sorry

**Comment by croussey** [comment]
![Capture d’écran du 2024-12-17 14-39-41](https://github.com/user-attachments/assets/667c3aa3-93cd-4d0e-80c3-79061ba10876)

**Comment by croussey** [comment]
does it means it is my chrome parameter that change the presentation of labels?

**Comment by dgarijo** [comment]
I think you may need to shift reload the page (it may be showing a cached version). I see the following:
![image](https://github.com/user-attachments/assets/14c17127-cd73-43b8-a492-8d16aede2084)
When I open https://rdf.codex.cati.inrae.fr/bag-def/index-fr.html

**Comment by croussey** [comment]
If I change the browser to a firefox one, it works.

**Comment by croussey** [comment]
Thanks for your help. Sorry for the inconvenient. Best Regards

**Comment by dgarijo** [comment]
No worries. One of the screenshots I uploaded is from Chrome ;)
